/**
 * Media Request Schemas
 * 
 * Only request validation schemas are needed here.
 * Response schemas are auto-generated by createCrudRouter.
 */

import { BASE_FOLDERS } from './media.config.js';

/**
 * Content types for image processing presets
 */
export const CONTENT_TYPES = ['product', 'category', 'banner', 'avatar', 'default'];

/**
 * Schema options for BaseController (protects system-managed fields)
 */
export const mediaSchemaOptions = {
  fieldRules: {
    url: { systemManaged: true },
    key: { systemManaged: true },
    size: { systemManaged: true },
    mimeType: { systemManaged: true },
    dimensions: { systemManaged: true },
    variants: { systemManaged: true },
    uploadedBy: { systemManaged: true },
  },
};

// Folder path pattern: must start with allowed base folder
const baseFolderPattern = `^(${BASE_FOLDERS.join('|')})(/[a-zA-Z0-9_-]+)*$`;

/**
 * Request schemas for validation
 */
export const mediaSchemas = {
  // List query params (optional filters)
  list: {
    querystring: {
      type: 'object',
      properties: {
        page: { type: 'integer', minimum: 1 },
        after: { type: 'string', description: 'Cursor for keyset pagination' },
        limit: { type: 'integer', minimum: 1, maximum: 100 },
        folder: { type: 'string', pattern: baseFolderPattern },
        baseFolder: { type: 'string', enum: BASE_FOLDERS },
        mimeType: { type: 'string' },
        contentType: { type: 'string', enum: CONTENT_TYPES },
        search: { type: 'string' },
        sort: { type: 'string' },
      },
    },
  },

  // Update (PATCH /:id)
  update: {
    body: {
      type: 'object',
      properties: {
        alt: { type: 'string', maxLength: 255 },
        title: { type: 'string', maxLength: 255 },
        description: { type: 'string', maxLength: 1000 },
        folder: { type: 'string', pattern: baseFolderPattern },
      },
      additionalProperties: false,
    },
  },

  // Folder param for folder routes
  folderParam: {
    params: {
      type: 'object',
      properties: {
        folder: { type: 'string', minLength: 1 },
      },
      required: ['folder'],
    },
  },

  // Bulk delete
  bulkDelete: {
    body: {
      type: 'object',
      properties: {
        ids: { 
          type: 'array', 
          items: { type: 'string' }, 
          minItems: 1, 
          maxItems: 100,
          description: 'Array of media IDs to delete',
        },
      },
      required: ['ids'],
      additionalProperties: false,
    },
  },

  // Move to folder
  move: {
    body: {
      type: 'object',
      properties: {
        ids: { 
          type: 'array', 
          items: { type: 'string' }, 
          minItems: 1, 
          maxItems: 100,
        },
        targetFolder: { 
          type: 'string', 
          pattern: baseFolderPattern,
          description: 'Target folder path (e.g., products/featured)',
        },
      },
      required: ['ids', 'targetFolder'],
      additionalProperties: false,
    },
  },
};
