/**
 * Stock Request Resource — Arc CRUD + Stripe Actions
 *
 * CRUD (list, get, create, update, delete) auto-generated by Arc's BaseController.
 * State transitions (submit_for_approval/decide/fulfill/cancel) declared via the
 * `actions` block below → mounted as `POST /:id/action { action: ... }`.
 *
 * Approval gate (`submit_for_approval` + `decide`) is contributed by the
 * shared `withApprovalChain` preset. Replaces the hand-rolled `approve` /
 * `reject` actions. The preset advances the chain; `onApproved` /
 * `onRejected` flip the coarse `status` field and capture review metadata
 * so existing list/filter UIs that key off `status` keep working.
 *
 * `fulfill` / `cancel` remain unchanged — they're post-approval lifecycle.
 */
import { defineResource } from '@classytic/arc';
import type { Repository } from '@classytic/mongokit';
import { createMongooseAdapter } from '@classytic/mongokit/adapter';
import { requireRoles } from '@classytic/arc/permissions';
import { QueryParser } from '@classytic/mongokit';
import mongoose from 'mongoose';
import permissions from '#config/permissions.js';
import {
  withApprovalChain,
  type ApprovableDoc,
} from '#core/approval/with-approval-chain.js';
import { createPolicyChainResolver } from '#resources/approval/policy-resolver.js';
import { getTransferEngine } from '#resources/inventory/_engines/transfer.engine.js';
import { buildTransferCtx } from '#resources/inventory/_engines/ctx.js';
import StockRequest from './models/stock-request.model.js';
import stockRequestController from './stock-request.controller.js';
import stockRequestRepository from './stock-request.repository.js';
import {
  cancelActionSchema,
  createSchema,
  fulfillActionSchema,
} from './stock-request.schemas.js';
import stockRequestService from './stock-request.service.js';

const queryParser = new QueryParser({
  maxLimit: 100,
  allowedFilterFields: ['status', 'priority', 'requestingBranch', 'fulfillingBranch'],
  allowedSortFields: ['createdAt', 'updatedAt', 'status', 'priority', 'requestNumber'],
});

/**
 * Local typed view of a StockRequest document. Extends `ApprovableDoc` so the
 * preset reads `doc.approvals` natively without string-keyed lookups (P7).
 */
interface StockRequestDoc extends ApprovableDoc {
  organizationId?: string;
  requestingBranch?: mongoose.Types.ObjectId;
  status: string;
  priority?: string;
  reason?: string;
}

function toObjectId(actorId: string | null): mongoose.Types.ObjectId | null {
  return actorId ? new mongoose.Types.ObjectId(actorId) : null;
}

const stockRequestResource = defineResource({
  name: 'stock-request',
  audit: true,
  displayName: 'Stock Requests',
  tag: 'Inventory - Stock Requests',
  prefix: '/inventory/requests',

  adapter: createMongooseAdapter(StockRequest, stockRequestRepository),
  queryParser,
  controller: stockRequestController,

  permissions: {
    list: permissions.inventory.stockRequestView,
    get: permissions.inventory.stockRequestView,
    create: permissions.inventory.stockRequestCreate,
    update: permissions.inventory.stockRequestCreate,
    delete: requireRoles('admin'),
  },

  // Zod v4 — Arc auto-converts. The service still does the catalog lookup
  // and sets requestNumber + requestedBy, but shape now fails at the gateway.
  customSchemas: {
    create: { body: createSchema.body },
  },

  actions: {
    // Approval gate — `submit_for_approval` + `decide` come from the shared
    // `withApprovalChain` preset. The legacy `approve` / `reject` per-action
    // handlers are gone. The preset advances the chain; the kernel-side
    // allocation work (setting `quantityApproved` per item, status flip,
    // `reviewedBy` / `reviewedAt` / `reviewNotes`, statusHistory push) runs
    // in `onApproved`. Note: the legacy `approveRequest` accepted a per-line
    // `items: ApprovedItem[]` parameter so an approver could trim quantities
    // at decision time. The preset's `decide` schema accepts only `note` —
    // adjusted-quantity-on-approve is a follow-up redesign (chain-decide
    // payload extension). For now, every approved item defaults to
    // `quantityRequested`.
    //
    // The mongokit `Repository<IStockRequest>` types loosely against the
    // raw model interface; one cast at the boundary lets the preset see the
    // `ApprovableDoc` shape. (P7: doc.approvals is canonical.)
    ...withApprovalChain<StockRequestDoc>({
      subjectType: 'stock_request',
      repository: stockRequestRepository as unknown as Repository<StockRequestDoc>,
      // Only `pending` requests may enter the approval pipeline. After a
      // chain is `rejected`, the preset's chain-state check still allows a
      // fresh chain to be attached for resubmission while the doc itself
      // stays in its terminal lifecycle state.
      allowedSubmitStatus: ['pending'],
      // `status` is the default — preset reads `doc.status` natively.
      permissions: {
        submit: permissions.inventory.stockRequestApprove,
        decide: permissions.inventory.stockRequestApprove,
      },
      toEvaluationContext: (doc) => ({
        branchId: String(doc.organizationId ?? doc.requestingBranch ?? ''),
        ...(doc.priority ? { priority: doc.priority } : {}),
        ...(doc.reason ? { reason: doc.reason } : {}),
      }),
      resolveChain: createPolicyChainResolver(),
      // Chain approved → run the kernel-side allocation that the legacy
      // `approveRequest` did, minus the `items` override (see comment above).
      // We use the model directly here rather than the service so we don't
      // re-validate `status === 'pending'` (the preset already gated submit
      // on that, and the chain is what advanced state).
      onApproved: async (doc, ctx) => {
        const fresh = await StockRequest.findById(String(doc._id));
        if (!fresh) return undefined;
        for (const item of fresh.items) {
          if (!item.quantityApproved || item.quantityApproved <= 0) {
            item.quantityApproved = item.quantityRequested;
          }
        }
        fresh.status = 'approved';
        fresh.reviewedBy = toObjectId(ctx.actorId) ?? fresh.reviewedBy;
        fresh.reviewedAt = new Date();
        fresh.statusHistory.push({
          status: 'approved',
          actor: toObjectId(ctx.actorId) ?? undefined,
          timestamp: new Date(),
          notes: 'Approved via approval chain',
        });
        await fresh.save();
        return fresh.toObject() as unknown as StockRequestDoc;
      },
      // Chain rejected → mirror the legacy `rejectRequest` side effects.
      onRejected: async (doc, decision, ctx) => {
        const fresh = await StockRequest.findById(String(doc._id));
        if (!fresh) return undefined;
        fresh.status = 'rejected';
        fresh.reviewedBy = toObjectId(ctx.actorId) ?? fresh.reviewedBy;
        fresh.reviewedAt = new Date();
        fresh.reviewNotes = decision.note;
        fresh.statusHistory.push({
          status: 'rejected',
          actor: toObjectId(ctx.actorId) ?? undefined,
          timestamp: new Date(),
          notes: decision.note ?? 'Request rejected',
        });
        await fresh.save();
        return fresh.toObject() as unknown as StockRequestDoc;
      },
    }),

    fulfill: {
      handler: async (id, data, req) => {
        const engine = getTransferEngine();
        const ctx = buildTransferCtx(req);
        return engine.repositories.stockRequest.fulfill(
          id,
          data.transferId as string,
          ctx,
        );
      },
      permissions: permissions.inventory.stockRequestFulfill,
      schema: fulfillActionSchema,
    },

    cancel: {
      handler: async (id, data, req) => {
        const engine = getTransferEngine();
        const ctx = buildTransferCtx(req);
        return engine.repositories.stockRequest.cancel(id, data.reason as string | undefined, ctx);
      },
      permissions: permissions.inventory.stockRequestCancel,
      schema: cancelActionSchema,
    },
  },

  routes: [
    {
      method: 'GET' as const,
      path: '/pending',
      summary: 'Get pending requests for review',
      permissions: permissions.inventory.stockRequestApprove,
      raw: true,
      handler: async (_req: any, reply: any) => {
        const result = await stockRequestService.getPendingForReview();
        reply.send(result);
      },
    },
  ],
});

export default stockRequestResource;
