/**
 * Stock Request Resource — Arc CRUD + Stripe Actions
 *
 * CRUD (list, get, create, update, delete) auto-generated by Arc's BaseController.
 * State transitions (approve/reject/fulfill/cancel) declared via the `actions`
 * block below → mounted as `POST /:id/action { action: ... }`.
 */
import { defineResource } from '@classytic/arc';
import { requireRoles } from '@classytic/arc/permissions';
import { QueryParser } from '@classytic/mongokit';
import permissions from '#config/permissions.js';
import { createAdapter } from '#shared/adapter.js';
import StockRequest from './models/stock-request.model.js';
import stockRequestController from './stock-request.controller.js';
import stockRequestRepository from './stock-request.repository.js';
import stockRequestService from './stock-request.service.js';

const queryParser = new QueryParser({
  maxLimit: 100,
  allowedFilterFields: ['status', 'priority', 'requestingBranch', 'fulfillingBranch'],
  allowedSortFields: ['createdAt', 'updatedAt', 'status', 'priority', 'requestNumber'],
});

const stockRequestResource = defineResource({
  name: 'stock-request',
  audit: true,
  displayName: 'Stock Requests',
  tag: 'Inventory - Stock Requests',
  prefix: '/inventory/requests',

  adapter: createAdapter(StockRequest, stockRequestRepository),
  queryParser,
  controller: stockRequestController,

  permissions: {
    list: permissions.inventory.stockRequestView,
    get: permissions.inventory.stockRequestView,
    create: permissions.inventory.stockRequestCreate,
    update: permissions.inventory.stockRequestCreate,
    delete: requireRoles('admin'),
  },

  // Tight create-body schema. The service still does the catalog lookup and
  // sets requestNumber + requestedBy, but shape now fails at the gateway
  // instead of deep in the service.
  customSchemas: {
    create: {
      body: {
        type: 'object',
        required: ['items'],
        additionalProperties: false,
        properties: {
          requestingBranchId: { type: 'string' },
          fulfillingBranchId: { type: 'string' },
          priority: {
            type: 'string',
            enum: ['low', 'normal', 'high', 'urgent'],
          },
          reason: { type: 'string' },
          expectedDate: { type: 'string', format: 'date-time' },
          notes: { type: 'string' },
          items: {
            type: 'array',
            minItems: 1,
            items: {
              type: 'object',
              required: ['productId', 'quantity'],
              additionalProperties: false,
              properties: {
                productId: { type: 'string' },
                variantSku: { type: ['string', 'null'] },
                quantity: { type: 'number', minimum: 0 },
                notes: { type: 'string' },
              },
            },
          },
        },
      },
    },
  },

  schemaOptions: {
    fieldRules: {
      requestNumber: { systemManaged: true },
      status: { systemManaged: true },
      statusHistory: { systemManaged: true },
      requestedBy: { systemManaged: true },
      reviewedBy: { systemManaged: true },
      fulfilledBy: { systemManaged: true },
    },
  },

  actions: {
    approve: {
      handler: async (id, data, req) => {
        const uid = String(req.user?._id || req.user?.id || '');
        return stockRequestService.approveRequest(id, data.items as any, data.reviewNotes as string | undefined, uid);
      },
      permissions: permissions.inventory.stockRequestApprove,
      schema: { items: { type: 'array' }, reviewNotes: { type: 'string' } },
    },
    reject: {
      handler: async (id, data, req) => {
        const uid = String(req.user?._id || req.user?.id || '');
        return stockRequestService.rejectRequest(id, data.reason as string | undefined, uid);
      },
      permissions: permissions.inventory.stockRequestApprove,
      schema: { reason: { type: 'string' } },
    },
    fulfill: {
      handler: async (id, data, req) => {
        const uid = String(req.user?._id || req.user?.id || '');
        return stockRequestService.fulfillRequest(id, data, uid);
      },
      permissions: permissions.inventory.stockRequestFulfill,
      schema: { items: { type: 'array' } },
    },
    cancel: {
      handler: async (id, data, req) => {
        const uid = String(req.user?._id || req.user?.id || '');
        return stockRequestService.cancelRequest(id, data.reason as string | undefined, uid);
      },
      permissions: permissions.inventory.stockRequestCancel,
      schema: { reason: { type: 'string' } },
    },
  },

  routes: [
    {
      method: 'GET' as const,
      path: '/pending',
      summary: 'Get pending requests for review',
      permissions: permissions.inventory.stockRequestApprove,
      raw: true,
      handler: async (_req: any, reply: any) => {
        const result = await stockRequestService.getPendingForReview();
        reply.send({ success: true, ...result });
      },
    },
  ],
});

export default stockRequestResource;
