import { BaseController, type RequestWithExtras, type IRequestContext, type IControllerResponse } from '@classytic/arc';
import type { FastifyReply } from 'fastify';
import categoryRepository from './category.repository.js';
import type { ICategory } from './category.model.js';
import { NotFoundError, ConflictError } from '#shared/utils/errors.js';

/**
 * Category Controller
 *
 * Extends BaseController for standard CRUD.
 * Slug lookup and tree operations now handled by Arc presets.
 */
class CategoryController extends BaseController<ICategory> {
  constructor() {
    super(categoryRepository);

    this.syncProductCounts = this.syncProductCounts.bind(this);
  }

  // Note: getBySlug and getTree are now auto-generated by Arc presets

  /**
   * Recalculate product counts for all categories
   */
  async syncProductCounts(_req: RequestWithExtras, reply: FastifyReply): Promise<void> {
    const result = await categoryRepository.recalculateAllCounts();
    return reply.send({ success: true, data: result });
  }

  /**
   * Override delete to check product count before allowing deletion
   */
  async delete(
    context: IRequestContext,
  ): Promise<IControllerResponse<{ message: string; id?: string; soft?: boolean }>> {
    let category: ICategory | null;
    try {
      category = await categoryRepository.getById(context.params.id);
    } catch {
      throw new NotFoundError('Category not found');
    }

    if (!category) {
      throw new NotFoundError('Category not found');
    }

    if (category.productCount > 0) {
      throw new ConflictError(`Cannot delete: ${category.productCount} products still use this category`);
    }

    await categoryRepository.delete(context.params.id);

    return {
      success: true,
      data: { message: 'Category deleted' },
      status: 200,
    };
  }
}

export default new CategoryController();
