/**
 * Stock Package Resource (standard+) — container management.
 *
 * Packages are containers (boxes, cartons, pallets) that group stock.
 * Supports nesting, pack/unpack, and atomic relocate (package + all
 * contents together).
 *
 * Template shape:
 *   - `adapter` for list/get/delete
 *   - `PackageController` overrides `create` → `services.package.create`
 *     (generates `name` + `barcode` + initial state)
 *   - `routes:` (raw) for the 5 stable service endpoints the SDK calls:
 *     `/contents`, `/nest`, `/unnest`, `/pack`, `/unpack`, `/relocate`
 *   - `disabledRoutes: ['update']` — packages mutate via the verbs above
 */

import { defineResource, BaseController } from '@classytic/arc';
import type { IRequestContext, IControllerResponse } from '@classytic/arc';
import { QueryParser } from '@classytic/mongokit';
import type { FastifyReply, FastifyRequest } from 'fastify';
import permissions from '#config/permissions.js';
import { createFlowAdapter } from '#shared/flow-adapter.js';
import { flow, flowCtxFromArcReq, flowCtxGuard, standardModeGuard } from '../shared/helpers.js';

class PackageController extends BaseController {
  async create(req: IRequestContext): Promise<IControllerResponse<Record<string, unknown>>> {
    const ctx = flowCtxFromArcReq(req);
    // biome-ignore lint/suspicious/noExplicitAny: service contract opaque
    const body = req.body as any;
    const pkg = await flow().services.package.create(body, ctx);
    return { success: true, data: pkg as unknown as Record<string, unknown>, status: 201 };
  }
}

export function createStockPackageResource() {
  const engine = flow();

  return defineResource({
    name: 'stock-package',
    displayName: 'Packages',
    tag: 'Warehouse - Packages',
    prefix: '/inventory/packages',
    tenantField: 'organizationId',

    adapter: createFlowAdapter(engine.models.StockPackage, engine.repositories.package, {
      // `name` + `barcode` are server-generated by `services.package.create`
      // (barcode auto-assigned from a sequence if the client omits it; name
      // derives from barcode). Keeping them out of the create body is the
      // whole reason for the service layer.
      fieldRules: {
        name: { systemManaged: true },
        barcode: { systemManaged: true },
      },
    }),

    controller: new PackageController(engine.repositories.package),
    disabledRoutes: ['update'],

    queryParser: new QueryParser({
      maxLimit: 100,
      allowedFilterFields: ['locationId', 'parentPackageId', 'packageUse', 'packageTypeId'],
    }),
    routeGuards: [standardModeGuard.preHandler],

    permissions: {
      list: permissions.inventory.packageView,
      get: permissions.inventory.packageView,
      create: permissions.inventory.packageManage,
      update: permissions.inventory.packageManage, // ignored (route disabled)
      delete: permissions.inventory.packageManage,
    },

    routes: [
      {
        method: 'GET',
        path: '/:id/contents',
        summary: 'Get package contents',
        description: 'List child packages and stock quants inside this package.',
        permissions: permissions.inventory.packageView,
        raw: true,
        preHandler: [flowCtxGuard.preHandler],
        handler: async (req: FastifyRequest, reply: FastifyReply) => {
          const { id } = req.params as { id: string };
          const ctx = flowCtxGuard.from(req);
          const contents = await flow().services.package.getContents(id, ctx);
          return reply.send({ success: true, data: contents });
        },
      },
      {
        method: 'POST',
        path: '/:id/nest',
        summary: 'Nest a package inside another',
        permissions: permissions.inventory.packageManage,
        raw: true,
        preHandler: [flowCtxGuard.preHandler],
        handler: async (req: FastifyRequest, reply: FastifyReply) => {
          const { id } = req.params as { id: string };
          const ctx = flowCtxGuard.from(req);
          const { childPackageId } = req.body as { childPackageId: string };
          await flow().services.package.nest(childPackageId, id, ctx);
          return reply.send({ success: true, data: { nested: true } });
        },
      },
      {
        method: 'POST',
        path: '/:id/unnest',
        summary: 'Remove package from parent',
        permissions: permissions.inventory.packageManage,
        raw: true,
        preHandler: [flowCtxGuard.preHandler],
        handler: async (req: FastifyRequest, reply: FastifyReply) => {
          const { id } = req.params as { id: string };
          const ctx = flowCtxGuard.from(req);
          await flow().services.package.unnest(id, ctx);
          return reply.send({ success: true, data: { unnested: true } });
        },
      },
      {
        method: 'POST',
        path: '/:id/pack',
        summary: 'Pack items into package',
        description:
          'Pack stock items into a package. Creates moves with resultPackageId for accurate quant tracking.',
        permissions: permissions.inventory.packageManage,
        raw: true,
        preHandler: [flowCtxGuard.preHandler],
        handler: async (req: FastifyRequest, reply: FastifyReply) => {
          const { id } = req.params as { id: string };
          const ctx = flowCtxGuard.from(req);
          const { lines } = req.body as {
            lines: Array<{ skuRef: string; lotId?: string; quantity: number }>;
          };
          const pkg = await flow().services.package.pack(id, lines, ctx);
          return reply.send({ success: true, data: pkg });
        },
      },
      {
        method: 'POST',
        path: '/:id/unpack',
        summary: 'Unpack all items from package',
        description: 'Remove all stock from package. Quants become loose at the same location.',
        permissions: permissions.inventory.packageManage,
        raw: true,
        preHandler: [flowCtxGuard.preHandler],
        handler: async (req: FastifyRequest, reply: FastifyReply) => {
          const { id } = req.params as { id: string };
          const ctx = flowCtxGuard.from(req);
          await flow().services.package.unpack(id, ctx);
          return reply.send({ success: true, data: { unpacked: true } });
        },
      },
      {
        method: 'POST',
        path: '/:id/relocate',
        summary: 'Relocate package to new location',
        description: 'Atomically moves the package and all its contents to a new location.',
        permissions: permissions.inventory.packageManage,
        raw: true,
        preHandler: [flowCtxGuard.preHandler],
        handler: async (req: FastifyRequest, reply: FastifyReply) => {
          const { id } = req.params as { id: string };
          const ctx = flowCtxGuard.from(req);
          const { destinationLocationId } = req.body as { destinationLocationId: string };
          const group = await flow().services.package.relocate(id, destinationLocationId, ctx);
          return reply.send({ success: true, data: group });
        },
      },
      // ── LPN (License Plate Number) identity verbs ─────────────────────
      // These operate on the `StockPackage` row directly (no stock moves).
      // They are the physical-container identity lifecycle; `/pack`,
      // `/unpack`, `/relocate` above handle the stock-movement lifecycle.
      {
        method: 'POST',
        path: '/:id/assign-lpn',
        summary: 'Stamp an LPN code on a package (one-time)',
        description:
          'Body: { lpnCode, assignedBy? }. Fails if pkg already has an lpnCode. Host owns the code format (SSCC, internal prefix, carrier tracking).',
        permissions: permissions.inventory.lpnAssign,
        raw: true,
        preHandler: [flowCtxGuard.preHandler],
        handler: async (req: FastifyRequest, reply: FastifyReply) => {
          const { id } = req.params as { id: string };
          const ctx = flowCtxGuard.from(req);
          const body = req.body as { lpnCode: string; assignedBy?: string };
          const updated = await flow().repositories.package.assignLpn(
            {
              packageId: id,
              lpnCode: body.lpnCode,
              ...(body.assignedBy !== undefined ? { assignedBy: body.assignedBy } : {}),
            },
            ctx,
          );
          return reply.send({ success: true, data: updated });
        },
      },
      {
        method: 'POST',
        path: '/:id/seal',
        summary: 'Seal a package (freezes contents — pre-dispatch)',
        description:
          'Body: { sealedBy? }. After seal, nest() into this package fails. Unseal is intentionally not a primitive.',
        permissions: permissions.inventory.lpnSeal,
        raw: true,
        preHandler: [flowCtxGuard.preHandler],
        handler: async (req: FastifyRequest, reply: FastifyReply) => {
          const { id } = req.params as { id: string };
          const ctx = flowCtxGuard.from(req);
          const body = (req.body ?? {}) as { sealedBy?: string };
          const updated = await flow().repositories.package.seal(
            {
              packageId: id,
              ...(body.sealedBy !== undefined ? { sealedBy: body.sealedBy } : {}),
            },
            ctx,
          );
          return reply.send({ success: true, data: updated });
        },
      },
    ],
  });
}
