/**
 * SettlementImport Resource — Arc CRUD + actions.
 *
 * CRUD auto-generated by Arc adapter. Three Stripe-style actions handle the
 * lifecycle:
 *   - POST /:id/action { action: 'post' }    — create the settlement JE
 *   - POST /:id/action { action: 'match' }   — run auto-match for this import
 *   - POST /:id/action { action: 'cancel' }  — finance-side undo (pre-post only)
 *
 * Manual leg-match is a separate route (`PATCH /:id/legs/:legId/match`)
 * because it takes per-leg params and isn't a state transition on the parent.
 */

import { defineResource } from '@classytic/arc';
import { createMongooseAdapter } from '@classytic/mongokit/adapter';
import { QueryParser } from '@classytic/mongokit';
import type { FastifyReply, FastifyRequest } from 'fastify';
import { groups } from '#config/permissions/roles.js';
import { requireAuth, requireRoles } from '#shared/permissions.js';
import { orgScoped } from '#shared/presets/index.js';
import SettlementImport from './settlement-import.model.js';
import settlementImportRepository from './settlement-import.repository.js';
import {
  cancelImport,
  postImport,
  recordImport,
  SettlementValidationError,
} from './settlement.service.js';
import { manualMatchLeg, matchSettlementLegs } from './settlement-matcher.service.js';
import { parseSettlementCsv } from './settlement-csv.parsers.js';
import type { SettlementProvider } from './settlement-import.model.js';
import { NotFoundError, ValidationError } from '@classytic/arc/utils';

const queryParser = new QueryParser({
  maxLimit: 200,
  allowedFilterFields: [
    'provider',
    'clearingAccountCode',
    'status',
    'statementDate',
    'externalRef',
    'organizationId',
  ],
  allowedSortFields: ['statementDate', 'createdAt', 'totalGross', 'totalNet'],
});

const writeRoles = requireRoles(groups.platformAdmin);

const settlementResource = defineResource({
  name: 'settlement-import',
  audit: true,
  displayName: 'Settlement Imports',
  tag: 'Accounting - Settlements',
  prefix: '/accounting/settlements',
  adapter: createMongooseAdapter(SettlementImport, settlementImportRepository),
  queryParser,
  presets: [orgScoped],
  permissions: {
    list: requireAuth(),
    get: requireAuth(),
    create: writeRoles,
    update: writeRoles,
    delete: writeRoles,
  },

  actions: {
    post: {
      handler: async (id: string, data: unknown, req: FastifyRequest) => {
        try {
          const actorId = (req as unknown as { user?: { _id?: string } }).user?._id;
          // Default: create JE in draft (finance reviews + posts via the
          // journal-entry endpoint). Explicit `autoPost: true` for trusted
          // flows (API reconciliation, nightly cron) that don't need review.
          const autoPost = (data as { autoPost?: boolean } | undefined)?.autoPost === true;
          const result = await postImport(id, { actorId, autoPost });
          return { ...result };
        } catch (err) {
          if (err instanceof SettlementValidationError) {
            throw new ValidationError(err.message);
          }
          throw err;
        }
      },
      permissions: writeRoles,
    },
    match: {
      handler: async (id: string, _data: unknown, req: FastifyRequest) => {
        const orgId = (req as unknown as { scope?: { organizationId?: string } }).scope
          ?.organizationId;
        if (!orgId) throw new ValidationError('Organization context required.');
        // Scope match to a single import by reading its clearing code first.
        const doc = await settlementImportRepository.getById(id);
        if (!doc) throw new NotFoundError('SettlementImport not found.');
        const summary = await matchSettlementLegs(orgId, {
          clearingAccountCode: doc.clearingAccountCode,
        });
        return { summary };
      },
      permissions: writeRoles,
    },
    cancel: {
      handler: async (id: string, data: unknown) => {
        try {
          const reason = (data as { reason?: string } | undefined)?.reason;
          await cancelImport(id, reason);
          return { ok: true };
        } catch (err) {
          if (err instanceof SettlementValidationError) {
            throw new ValidationError(err.message);
          }
          throw err;
        }
      },
      permissions: writeRoles,
    },
  },

  routes: [
    {
      method: 'PATCH' as const,
      path: '/:id/legs/:legId/match',
      summary: 'Manually pin a settlement leg to a journal-entry line.',
      permissions: writeRoles,
      raw: true,
      handler: async (req: FastifyRequest, reply: FastifyReply) => {
        const { id, legId } = req.params as { id: string; legId: string };
        const body = req.body as { journalEntryId?: string; journalItemIndex?: number };
        if (!body?.journalEntryId || typeof body?.journalItemIndex !== 'number') {
          throw new ValidationError('journalEntryId and journalItemIndex are required.');
        }
        await manualMatchLeg({
          importId: id,
          legId,
          journalEntryId: body.journalEntryId,
          journalItemIndex: body.journalItemIndex,
        });
        return reply.send(null);
      },
    },
    {
      method: 'POST' as const,
      path: '/import-csv',
      summary: 'Parse a provider CSV statement and create a SettlementImport (status=pending).',
      permissions: writeRoles,
      raw: true,
      handler: async (req: FastifyRequest, reply: FastifyReply) => {
        const orgId = (req as unknown as { scope?: { organizationId?: string } }).scope
          ?.organizationId;
        if (!orgId) {
          throw new ValidationError('Organization context required.');
        }
        const body = req.body as {
          provider?: SettlementProvider;
          externalRef?: string;
          statementDate?: string;
          csv?: string;
          notes?: string;
        };
        if (!body?.provider || !body?.externalRef || !body?.statementDate || !body?.csv) {
          throw new ValidationError('provider, externalRef, statementDate, and csv are required.');
        }
        const statementDate = new Date(body.statementDate);
        if (Number.isNaN(statementDate.getTime())) {
          throw new ValidationError('Invalid statementDate.');
        }
        try {
          const parsed = parseSettlementCsv(body.provider, body.csv);
          if (parsed.legs.length === 0) {
            throw new ValidationError('CSV produced zero legs.');
          }
          const actorId = (req as unknown as { user?: { _id?: string } }).user?._id;
          const doc = await recordImport({
            organizationId: orgId,
            provider: body.provider,
            externalRef: body.externalRef,
            statementDate,
            legs: parsed.legs,
            source: 'csv',
            uploadedBy: actorId,
            notes: body.notes,
          });
          return reply.send(doc);
        } catch (err) {
          if (err instanceof SettlementValidationError || err instanceof Error) {
            throw new ValidationError(err.message);
          }
          throw err;
        }
      },
    },
    {
      method: 'POST' as const,
      path: '/match-all',
      summary: 'Run auto-matcher across every unmatched leg in this branch.',
      permissions: writeRoles,
      raw: true,
      handler: async (req: FastifyRequest, reply: FastifyReply) => {
        const orgId = (req as unknown as { scope?: { organizationId?: string } }).scope
          ?.organizationId;
        if (!orgId) {
          throw new ValidationError('Organization context required.');
        }
        const body = (req.body ?? {}) as { clearingAccountCode?: string };
        const summary = await matchSettlementLegs(orgId, {
          clearingAccountCode: body.clearingAccountCode,
        });
        return reply.send(summary);
      },
    },
  ],
});

export default settlementResource;
