/**
 * Invoice Resource — Arc defineResource with MongoKit adapter.
 *
 * CRUD (list, get, create, update, delete) auto-generated by Arc's BaseController.
 * QueryParser gives free filtering by status, moveType, partnerId, paymentStatus.
 *
 * State transitions (post, cancel, void, record_payment, credit_note, etc.)
 * via the declarative `actions:` block — Arc auto-mounts POST /:id/action.
 *
 * Only custom routes (aging, receipt, dunning, recurring, document) are hand-wired.
 * Feature-gated: INVOICE_ENGINE env var.
 */

import { createMongooseAdapter, defineResource } from '@classytic/arc';
import { requireAuth, requireRoles } from '@classytic/arc/permissions';
import { buildCrudSchemasFromModel, QueryParser } from '@classytic/mongokit';
import config from '#config/index.js';
import {
  batchCancel,
  batchCreate,
  batchPost,
  batchRecordPayment,
  createReceipt,
  getAgingReport,
  getDocumentData,
  getOverdueInvoices,
  processDunning,
  processRecurring,
} from './invoice.handlers.js';

const authenticated = requireAuth();
const financeRoles = requireRoles('admin', 'finance_admin', 'finance_manager');

// Placeholder — auto-discovered by loadResources at boot.
// When engine is disabled, this is the final resource (empty).
// When engine is enabled, invoice.plugin.ts registers the full resource
// with adapter + action router after engine init.
const invoiceResource = defineResource({
  name: 'invoices',
  displayName: 'Invoices',
  tag: 'Accounting - Invoices',
  prefix: '/accounting/invoices',
  disableDefaultRoutes: true,
  routes: [],
  skipValidation: true,
});

export default invoiceResource;

/**
 * Build the full invoice resource AFTER engine init.
 * Called from invoice.plugin.ts with the engine's models + repos.
 */
export async function buildInvoiceResource(
  // biome-ignore lint/suspicious/noExplicitAny: engine models are loosely typed
  model: any,
  // biome-ignore lint/suspicious/noExplicitAny: engine repos are loosely typed
  repo: any,
) {
  const queryParser = new QueryParser({
    maxLimit: 200,
    allowedFilterFields: [
      'status',
      'moveType',
      'partnerId',
      'paymentStatus',
      'currency',
      'sourceType',
      'sourceId',
      'number',
      'quoteStatus',
      'taxMode',
      'approvalStatus',
    ],
    allowedSortFields: ['date', 'dueDate', 'totalAmount', 'number', 'createdAt'],
  });

  return defineResource({
    name: 'invoices-crud',
    displayName: 'Invoices',
    tag: 'Accounting - Invoices',
    prefix: '/accounting/invoices',

    actions: (await import('./invoice.actions.js')).invoiceActions,
    actionPermissions: financeRoles,

    // Arc auto-generates: GET /, GET /:id, POST /, PATCH /:id, DELETE /:id.
    // `softRequiredFields` feeds MongoKit's `buildCrudSchemasFromModel`
    // (via `#shared/adapter.ts`) — fields stay in the generated body schema
    // but leave the `required` array so clients may omit them. `currency`
    // defaults to BDT from the engine; the invoice numbering/status fields
    // are system-managed by the state machine and shouldn't block PATCH.
    adapter: createMongooseAdapter({
      model,
      repository: repo,
      schemaGenerator: (m, arcOptions) =>
        buildCrudSchemasFromModel(m, {
          ...(arcOptions as Record<string, unknown>),
          softRequiredFields: ['currency'],
        } as Parameters<typeof buildCrudSchemasFromModel>[1]),
    }),
    queryParser,

    permissions: {
      list: authenticated,
      get: authenticated,
      create: financeRoles,
      update: financeRoles,
      delete: financeRoles,
    },

    // `BaseController.create` calls the repository's base `create()` — it
    // does NOT route through the domain's `createDraft()` helper, so the
    // engine's `deps.currency` default never runs for HTTP clients. Mirror
    // the default here so a minimal POST /invoices payload saves cleanly.
    // (Domain callers — action router, workflows — still go through
    // `createDraft()` and get the same default.)
    hooks: {
      beforeCreate: async (ctx) => {
        const data = ctx.data as Record<string, unknown>;
        if (!data.currency) data.currency = 'BDT';
      },
    },

    schemaOptions: {
      excludeFields: ['journalEntryId', 'postedAt', 'paidAt', 'cancelledAt', 'voidedAt'],
      fieldRules: {
        number: { systemManaged: true },
        status: { systemManaged: true },
        paymentStatus: { systemManaged: true },
        untaxedAmount: { systemManaged: true },
        taxAmount: { systemManaged: true },
        totalAmount: { systemManaged: true },
        amountPaid: { systemManaged: true },
        amountDue: { systemManaged: true },
      },
    },

    // Only custom routes — CRUD + action router handled automatically
    routes: [
      {
        method: 'GET',
        path: '/aging',
        summary: 'Aging report (AR/AP)',
        permissions: authenticated,
        raw: true,
        handler: getAgingReport,
      },
      {
        method: 'GET',
        path: '/overdue',
        summary: 'List overdue invoices',
        permissions: authenticated,
        raw: true,
        handler: getOverdueInvoices,
      },
      {
        method: 'POST',
        path: '/receipt',
        summary: 'POS receipt shortcut',
        permissions: financeRoles,
        raw: true,
        handler: createReceipt,
      },
      {
        method: 'POST',
        path: '/dunning/process',
        summary: 'Process dunning reminders',
        permissions: financeRoles,
        raw: true,
        handler: processDunning,
      },
      // RecurringInvoice CRUD lives at /accounting/recurring-invoices —
      // see recurring-invoice.resource.ts. The /process workflow trigger
      // stays here because it fans out across active configs (not per-id).
      {
        method: 'POST',
        path: '/recurring/process',
        summary: 'Process scheduled recurring invoices',
        permissions: financeRoles,
        raw: true,
        handler: processRecurring,
      },
      {
        method: 'GET',
        path: '/:id/document',
        summary: 'Invoice document data (PDF/print)',
        permissions: authenticated,
        raw: true,
        handler: getDocumentData,
      },
      {
        method: 'GET',
        path: '/:id/pdf',
        summary: 'Server-rendered Mushak 6.3 PDF download',
        permissions: authenticated,
        raw: true,
        handler: (await import('./invoice.handlers.js')).downloadPdf,
      },
      // Pending approvals: use auto-CRUD list with `?approvalStatus=pending`
      // (already in queryParser.allowedFilterFields). No custom route needed.
      // ── Batch Operations ──
      {
        method: 'POST',
        path: '/batch/create',
        summary: 'Batch create draft invoices',
        permissions: financeRoles,
        raw: true,
        handler: batchCreate,
      },
      {
        method: 'POST',
        path: '/batch/post',
        summary: 'Batch post invoices',
        permissions: financeRoles,
        raw: true,
        handler: batchPost,
      },
      {
        method: 'POST',
        path: '/batch/record-payment',
        summary: 'Batch record payments',
        permissions: financeRoles,
        raw: true,
        handler: batchRecordPayment,
      },
      {
        method: 'POST',
        path: '/batch/cancel',
        summary: 'Batch cancel invoices',
        permissions: financeRoles,
        raw: true,
        handler: batchCancel,
      },
      // PaymentTerm CRUD + /:id/schedule live at /accounting/payment-terms —
      // see payment-term.resource.ts.
    ],
  });
}
