/**
 * Musok Resource — Mushak 6.3 VAT Invoice CRUD + Actions
 *
 * CRUD (list, get, delete) auto-generated by Arc via adapter.
 * Custom routes for generate, source-lookup, return, BIN validation.
 * State transitions (cancel) via declarative actions.
 */

import { createMongooseAdapter, defineResource } from '@classytic/arc';
import { requireAuth, requireRoles } from '@classytic/arc/permissions';
import {
  monthlyReturnParamsSchema,
  mushak63GenerateBodySchema,
  musokBySourceParamsSchema,
  validateBinParamsSchema,
} from '@classytic/bd-tax';
import { QueryParser } from '@classytic/mongokit';
import { z } from 'zod';
import { orgScoped } from '#shared/presets/index.js';
import {
  cancelMusokInvoice,
  generateMusokInvoice,
  getMonthlyReturn,
  getMusokBySource,
  validateBinEndpoint,
} from './musok.handlers.js';
import MusokInvoice from './musok.model.js';
import musokInvoiceRepository from './musok.repository.js';

const queryParser = new QueryParser({
  maxLimit: 100,
  allowedFilterFields: ['status', 'branchCode', 'serialYear', 'sourceModel', 'sourceId', 'buyer.name', 'buyer.bin'],
  allowedSortFields: ['createdAt', 'date', 'mushakSerial', 'grandTotal', 'serialNumber'],
});

const musokResource = defineResource({
  name: 'musok-invoice',
  displayName: 'Musok (VAT) Invoices',
  tag: 'Accounting - Musok',
  prefix: '/accounting/musok',
  audit: true,

  adapter: createMongooseAdapter(MusokInvoice, musokInvoiceRepository),
  queryParser,
  presets: [orgScoped],

  permissions: {
    list: requireAuth(),
    get: requireAuth(),
    create: requireRoles('admin', 'finance_admin'),
    update: requireRoles('admin'),
    delete: requireRoles('admin'),
  },

  schemaOptions: {
    fieldRules: {
      mushakSerial: { systemManaged: true },
      serialYear: { systemManaged: true },
      serialNumber: { systemManaged: true },
      totalValue: { systemManaged: true },
      totalSd: { systemManaged: true },
      totalVat: { systemManaged: true },
      grandTotal: { systemManaged: true },
      status: { systemManaged: true },
      cancelledAt: { systemManaged: true },
    },
  },

  actions: {
    cancel: {
      handler: async (id, data) => cancelMusokInvoice(id, data),
      permissions: requireRoles('admin', 'finance_admin'),
      schema: z.object({ reason: z.string().optional() }),
    },
  },

  // Custom routes — NOT reimplemented CRUD.
  // All schemas come from @classytic/bd-tax (canonical contract); Arc
  // auto-generates OpenAPI, MCP tools, and SDK types from them.
  routes: [
    {
      method: 'POST' as const,
      path: '/generate',
      summary: 'Generate Mushak 6.3 VAT invoice from order/invoice data',
      permissions: requireRoles('admin', 'finance_admin', 'cashier'),
      raw: true,
      schema: { body: mushak63GenerateBodySchema },
      handler: generateMusokInvoice,
    },
    {
      method: 'GET' as const,
      path: '/source/:sourceModel/:sourceId',
      summary: 'Get Musok invoice by source (Order/JournalEntry)',
      permissions: requireAuth(),
      raw: true,
      schema: { params: musokBySourceParamsSchema },
      handler: getMusokBySource,
    },
    {
      method: 'GET' as const,
      path: '/return/:period',
      summary: 'Monthly VAT / TOT return (branches on branch.businessType — Mushak 9.1 or 9.2)',
      permissions: requireRoles('admin', 'finance_admin'),
      raw: true,
      schema: { params: monthlyReturnParamsSchema },
      handler: getMonthlyReturn,
    },
    {
      method: 'GET' as const,
      path: '/validate-bin/:bin',
      summary: 'Validate a Bangladesh BIN (Business Identification Number)',
      permissions: requireAuth(),
      raw: true,
      schema: { params: validateBinParamsSchema },
      handler: validateBinEndpoint,
    },
  ],
});

export default musokResource;
