/**
 * Transaction Resource — @classytic/revenue v2
 *
 * Revenue v2 owns the model and repository. The resource just wires them
 * into Arc via `createAdapter` and exposes domain verbs as actions
 * (Stripe pattern — PACKAGE_RULES §27).
 *
 * CRUD is auto-generated by Arc from the adapter.
 * Reports are read-only custom routes using the model directly.
 */

import { defineResource } from '@classytic/arc';
import permissions from '#config/permissions.js';
import { createAdapter } from '#shared/adapter.js';
import { getResourcePermissions } from '#shared/permissions.js';
import { queryParser } from '#shared/query-parser.js';
import { ensureRevenueEngine } from '#shared/revenue/engine.js';
import { events } from './events.js';
import { getCashFlowReport, getCategoriesReport, getProfitLossReport } from './handlers/reports.handler.js';
import { getStatement } from './handlers/statement.handler.js';
import { buildTransactionCrudSchemas, transactionSchemaOptions } from './schemas.js';

// Top-level await — mongoose is connected before loadResources() runs.
// Same pattern as order.resource.ts. Replaces lazy `get adapter()` that
// would throw if the revenue plugin hadn't run yet.
const revenueEngine = await ensureRevenueEngine();
const transactionAdapter = createAdapter(
  revenueEngine.models.Transaction as never,
  revenueEngine.repositories.transaction as never,
);

const transactionResource = defineResource({
  name: 'transaction',
  audit: true,
  displayName: 'Transactions',
  tag: 'Transaction',
  prefix: '/transactions',

  adapter: transactionAdapter,
  queryParser,

  permissions: getResourcePermissions('transaction'),
  schemaOptions: {
    fieldRules: transactionSchemaOptions.fieldRules,
    query: transactionSchemaOptions.query,
  },
  customSchemas: buildTransactionCrudSchemas(revenueEngine.models.Transaction as never),

  actions: {
    verify: {
      handler: async (id: string, data: Record<string, unknown>, req: any) => {
        return revenueEngine.repositories.transaction.verify(
          id,
          { verifiedBy: req.user?.id ?? (data.verifiedBy as string) },
          { organizationId: req.scope?.organizationId, actorId: req.user?.id },
        );
      },
      permissions: permissions.transactions.manage,
      schema: {
        verifiedBy: { type: 'string' },
        notes: { type: 'string' },
      },
      description: 'Verify a pending payment',
    },

    refund: {
      handler: async (id: string, data: Record<string, unknown>, req: any) => {
        return revenueEngine.repositories.transaction.refund(
          id,
          (data.amount as number) ?? null,
          { reason: data.reason as string },
          { organizationId: req.scope?.organizationId, actorId: req.user?.id },
        );
      },
      permissions: permissions.transactions.manage,
      schema: {
        amount: { type: 'number', minimum: 1 },
        reason: { type: 'string', minLength: 3 },
      },
      description: 'Refund a verified transaction (full or partial)',
    },

    hold: {
      handler: async (id: string, data: Record<string, unknown>, req: any) => {
        return revenueEngine.repositories.transaction.hold(
          id,
          {
            amount: data.amount as number,
            reason: data.reason as string,
            holdUntil: data.holdUntil ? new Date(data.holdUntil as string) : undefined,
          },
          { organizationId: req.scope?.organizationId, actorId: req.user?.id },
        );
      },
      permissions: permissions.transactions.manage,
      schema: {
        amount: { type: 'number' },
        reason: { type: 'string' },
        holdUntil: { type: 'string', format: 'date-time' },
      },
      description: 'Place funds on escrow hold',
    },

    release: {
      handler: async (id: string, data: Record<string, unknown>, req: any) => {
        return revenueEngine.repositories.transaction.release(
          id,
          {
            recipientId: data.recipientId as string,
            recipientType: data.recipientType as string,
            amount: data.amount as number,
            reason: data.reason as string,
            releasedBy: req.user?.id,
          },
          { organizationId: req.scope?.organizationId, actorId: req.user?.id },
        );
      },
      permissions: permissions.transactions.manage,
      schema: {
        recipientId: { type: 'string' },
        recipientType: { type: 'string' },
        amount: { type: 'number' },
        reason: { type: 'string' },
      },
      description: 'Release held escrow funds',
    },

    split: {
      handler: async (id: string, data: Record<string, unknown>, req: any) => {
        return revenueEngine.repositories.transaction.split(id, data.rules as any[], {
          organizationId: req.scope?.organizationId,
          actorId: req.user?.id,
        });
      },
      permissions: permissions.transactions.manage,
      schema: {
        rules: { type: 'array' },
      },
      description: 'Split payment among recipients',
    },
  },

  routes: [
    {
      method: 'GET',
      path: '/statement',
      handler: getStatement as any,
      summary: 'Export transaction statement (CSV/JSON)',
      permissions: permissions.transactions.list,
      raw: true,
      schema: {
        querystring: {
          type: 'object',
          properties: {
            startDate: { type: 'string', format: 'date-time' },
            endDate: { type: 'string', format: 'date-time' },
            branchId: { type: 'string' },
            source: { type: 'string', enum: ['web', 'pos', 'api'] },
            status: { type: 'string' },
            format: { type: 'string', enum: ['csv', 'json'], default: 'csv' },
          },
        },
      },
    },
    {
      method: 'GET',
      path: '/reports/profit-loss',
      handler: getProfitLossReport as any,
      summary: 'Profit & Loss report',
      permissions: permissions.transactions.list,
      raw: true,
      schema: {
        querystring: {
          type: 'object',
          properties: {
            startDate: { type: 'string', format: 'date-time' },
            endDate: { type: 'string', format: 'date-time' },
          },
        },
      },
    },
    {
      method: 'GET',
      path: '/reports/categories',
      handler: getCategoriesReport as any,
      summary: 'Category breakdown',
      permissions: permissions.transactions.list,
      raw: true,
      schema: {
        querystring: {
          type: 'object',
          properties: {
            startDate: { type: 'string', format: 'date-time' },
            endDate: { type: 'string', format: 'date-time' },
            type: { type: 'string', enum: ['income', 'expense'] },
            limit: { type: 'integer', default: 10 },
          },
        },
      },
    },
    {
      method: 'GET',
      path: '/reports/cash-flow',
      handler: getCashFlowReport as any,
      summary: 'Cash flow trend',
      permissions: permissions.transactions.list,
      raw: true,
      schema: { querystring: { type: 'object', properties: { months: { type: 'integer', default: 6, maximum: 12 } } } },
    },
  ],

  events,
});

export default transactionResource;
