/**
 * Transfer Resource — Arc CRUD + Stripe Actions
 *
 * CRUD (list, get, create, update, delete) auto-generated by Arc's BaseController.
 * State transitions (approve/dispatch/in-transit/receive/cancel) via declarative actions.
 * Only truly custom routes (stats, export) are in routes.
 */
import { createMongooseAdapter, defineResource } from '@classytic/arc';
import { requireRoles } from '@classytic/arc/permissions';
import { QueryParser } from '@classytic/mongokit';
import permissions from '#config/permissions.js';
import Transfer from './models/transfer.model.js';
import transferController from './transfer.controller.js';
import transferRepository from './transfer.repository.js';
import {
  cancelActionSchema,
  createSchema,
  dispatchActionSchema,
  receiveActionSchema,
  updateSchema,
} from './transfer.schemas.js';
import transferService from './transfer.service.js';

const queryParser = new QueryParser({
  maxLimit: 100,
  allowedFilterFields: ['status', 'senderBranch', 'receiverBranch', 'transferType', 'documentType'],
  allowedSortFields: ['createdAt', 'updatedAt', 'status', 'documentNumber'],
});

const transferResource = defineResource({
  name: 'transfer',
  audit: true,
  displayName: 'Transfers',
  tag: 'Inventory - Transfers',
  prefix: '/inventory/transfers',

  adapter: createMongooseAdapter(Transfer, transferRepository),
  queryParser,
  controller: transferController,

  permissions: {
    list: permissions.inventory.transferView,
    get: permissions.inventory.transferView,
    create: permissions.inventory.transferCreate,
    update: permissions.inventory.transferCreate,
    delete: requireRoles('admin'),
  },

  // Zod v4 bodies — Arc auto-converts to JSON Schema at registration. Service
  // still resolves senderBranchId default and normalizes per-line metadata
  // (productName, variant lookup, etc.) but shape is enforced at the gateway.
  customSchemas: {
    create: { body: createSchema.body },
    update: { body: updateSchema.body },
  },

  actions: {
    approve: {
      handler: async (id, _data, req) => {
        const uid = String(req.user?._id || req.user?.id || '');
        return transferService.approveTransfer(id, uid);
      },
      permissions: permissions.inventory.transferApprove,
    },
    dispatch: {
      handler: async (id, data, req) => {
        const uid = String(req.user?._id || req.user?.id || '');
        return transferService.dispatchTransfer(id, (data.transport || data) as any, uid);
      },
      permissions: permissions.inventory.transferDispatch,
      // Transport details are optional — simple point-to-point transfers
      // can omit them entirely.
      schema: dispatchActionSchema,
    },
    'in-transit': {
      handler: async (id, _data, req) => {
        const uid = String(req.user?._id || req.user?.id || '');
        return transferService.markInTransit(id, uid);
      },
      permissions: permissions.inventory.transferDispatch,
    },
    receive: {
      handler: async (id, data, req) => {
        const uid = String(req.user?._id || req.user?.id || '');
        return transferService.receiveTransfer(id, (data.items || []) as any, uid);
      },
      permissions: permissions.inventory.transferReceive,
      // items optional — omitted means "receive everything in the dispatch".
      schema: receiveActionSchema,
    },
    cancel: {
      handler: async (id, data, req) => {
        const uid = String(req.user?._id || req.user?.id || '');
        return transferService.cancelTransfer(id, data.reason as string | undefined, uid);
      },
      permissions: permissions.inventory.transferCancel,
      schema: cancelActionSchema,
    },
  },

  routes: [
    {
      method: 'GET' as const,
      path: '/stats',
      summary: 'Transfer statistics',
      permissions: permissions.inventory.transferView,
      raw: true,
      handler: async (req: any, reply: any) => {
        const stats = await transferService.getStats(req.query);
        reply.send({ success: true, data: stats });
      },
    },
    {
      method: 'GET' as const,
      path: '/export',
      summary: 'Export transfers to CSV',
      permissions: permissions.inventory.transferView,
      raw: true,
      handler: async (req: any, reply: any) => {
        const { limit, ...filters } = req.query;
        const exportLimit = Math.min(parseInt(limit, 10) || 10000, 50000);
        const result = await transferService.listTransfers(filters, {
          limit: exportLimit,
          sort: '-createdAt',
          populate: true,
        });

        const csvRows: string[] = [
          'Transfer ID,Number,Type,Status,Sender,Receiver,Items,Quantity,Value,Created,Dispatched,Received',
        ];
        for (const t of (result.docs || []) as any[]) {
          const sender = typeof t.senderBranch === 'object' ? t.senderBranch?.name : t.senderBranch;
          const receiver = typeof t.receiverBranch === 'object' ? t.receiverBranch?.name : t.receiverBranch;
          csvRows.push(
            [
              t._id,
              t.documentNumber || '',
              t.transferType || '',
              t.status || '',
              sender || '',
              receiver || '',
              t.totalItems || 0,
              t.totalQuantity || 0,
              t.totalValue || 0,
              t.createdAt ? new Date(t.createdAt).toISOString() : '',
              t.dispatchedAt ? new Date(t.dispatchedAt).toISOString() : '',
              t.receivedAt ? new Date(t.receivedAt).toISOString() : '',
            ].join(','),
          );
        }

        reply.header('Content-Type', 'text/csv');
        reply.header(
          'Content-Disposition',
          `attachment; filename="transfers-${new Date().toISOString().split('T')[0]}.csv"`,
        );
        reply.send(csvRows.join('\n'));
      },
    },
  ],
});

export default transferResource;
