/**
 * Transfer Resource — Arc CRUD + Stripe Actions
 *
 * CRUD (list, get, create, update, delete) auto-generated by Arc's BaseController.
 * State transitions (approve/dispatch/in-transit/receive/cancel) via declarative actions.
 * Only truly custom routes (stats, export) are in routes.
 */
import { defineResource } from '@classytic/arc';
import { requireAuth, requireRoles } from '@classytic/arc/permissions';
import { QueryParser } from '@classytic/mongokit';
import permissions from '#config/permissions.js';
import { createAdapter } from '#shared/adapter.js';
import Transfer from './models/transfer.model.js';
import transferController from './transfer.controller.js';
import transferRepository from './transfer.repository.js';
import transferService from './transfer.service.js';

const queryParser = new QueryParser({
  maxLimit: 100,
  allowedFilterFields: ['status', 'senderBranch', 'receiverBranch', 'transferType', 'documentType'],
  allowedSortFields: ['createdAt', 'updatedAt', 'status', 'documentNumber'],
});

const transferResource = defineResource({
  name: 'transfer',
  audit: true,
  displayName: 'Transfers',
  tag: 'Inventory - Transfers',
  prefix: '/inventory/transfers',

  adapter: createAdapter(Transfer, transferRepository),
  queryParser,
  controller: transferController,

  permissions: {
    list: permissions.inventory.transferView,
    get: permissions.inventory.transferView,
    create: permissions.inventory.transferCreate,
    update: permissions.inventory.transferCreate,
    delete: requireRoles('admin'),
  },

  // Tight create-body schema. Service still resolves senderBranchId default
  // and normalizes per-line metadata (productName, variant lookup, etc.) but
  // shape is enforced at the gateway. `update` keeps the same item-array
  // schema for consistency.
  customSchemas: {
    create: {
      body: {
        type: 'object',
        required: ['receiverBranchId', 'items'],
        additionalProperties: false,
        properties: {
          senderBranchId: { type: 'string' },
          receiverBranchId: { type: 'string' },
          documentType: {
            type: 'string',
            enum: ['delivery_note', 'dispatch_note', 'delivery_slip'],
          },
          remarks: { type: 'string' },
          items: {
            type: 'array',
            minItems: 1,
            items: {
              type: 'object',
              required: ['productId', 'quantity'],
              additionalProperties: false,
              properties: {
                productId: { type: 'string' },
                variantSku: { type: ['string', 'null'] },
                quantity: { type: 'number', minimum: 0 },
                cartonNumber: { type: 'string' },
                sourceLocationId: { type: 'string' },
                destinationLocationId: { type: 'string' },
              },
            },
          },
        },
      },
    },
    update: {
      body: {
        type: 'object',
        additionalProperties: false,
        properties: {
          remarks: { type: 'string' },
          documentType: {
            type: 'string',
            enum: ['delivery_note', 'dispatch_note', 'delivery_slip'],
          },
          items: {
            type: 'array',
            items: {
              type: 'object',
              required: ['productId', 'quantity'],
              additionalProperties: false,
              properties: {
                productId: { type: 'string' },
                variantSku: { type: ['string', 'null'] },
                quantity: { type: 'number', minimum: 0 },
                cartonNumber: { type: 'string' },
                sourceLocationId: { type: 'string' },
                destinationLocationId: { type: 'string' },
              },
            },
          },
        },
      },
    },
  },

  schemaOptions: {
    fieldRules: {
      documentNumber: { systemManaged: true },
      status: { systemManaged: true },
      totalItems: { systemManaged: true },
      totalQuantity: { systemManaged: true },
      totalValue: { systemManaged: true },
      statusHistory: { systemManaged: true },
      createdBy: { systemManaged: true },
      approvedBy: { systemManaged: true },
      dispatchedBy: { systemManaged: true },
      receivedBy: { systemManaged: true },
    },
  },

  actions: {
    approve: {
      handler: async (id, _data, req) => {
        const uid = String(req.user?._id || req.user?.id || '');
        return transferService.approveTransfer(id, uid);
      },
      permissions: permissions.inventory.transferApprove,
    },
    dispatch: {
      handler: async (id, data, req) => {
        const uid = String(req.user?._id || req.user?.id || '');
        return transferService.dispatchTransfer(id, (data.transport || data) as any, uid);
      },
      permissions: permissions.inventory.transferDispatch,
      // Transport details are optional — callers can skip for simple
      // point-to-point transfers. Use the full JSON Schema form with an
      // empty `required` array so AJV accepts the payload when transport
      // is omitted (legacy field-map form treats every field as required).
      schema: {
        type: 'object',
        properties: { transport: { type: 'object', description: 'Transport details' } },
        required: [],
      },
    },
    'in-transit': {
      handler: async (id, _data, req) => {
        const uid = String(req.user?._id || req.user?.id || '');
        return transferService.markInTransit(id, uid);
      },
      permissions: permissions.inventory.transferDispatch,
    },
    receive: {
      handler: async (id, data, req) => {
        const uid = String(req.user?._id || req.user?.id || '');
        return transferService.receiveTransfer(id, (data.items || []) as any, uid);
      },
      permissions: permissions.inventory.transferReceive,
      // items optional — omitted means "receive everything in the dispatch".
      schema: {
        type: 'object',
        properties: { items: { type: 'array', description: 'Received items with quantities' } },
        required: [],
      },
    },
    cancel: {
      handler: async (id, data, req) => {
        const uid = String(req.user?._id || req.user?.id || '');
        return transferService.cancelTransfer(id, data.reason as string | undefined, uid);
      },
      permissions: permissions.inventory.transferCancel,
      schema: {
        type: 'object',
        properties: { reason: { type: 'string', description: 'Cancellation reason' } },
        required: [],
      },
    },
  },

  routes: [
    {
      method: 'GET' as const,
      path: '/stats',
      summary: 'Transfer statistics',
      permissions: permissions.inventory.transferView,
      raw: true,
      handler: async (req: any, reply: any) => {
        const stats = await transferService.getStats(req.query);
        reply.send({ success: true, data: stats });
      },
    },
    {
      method: 'GET' as const,
      path: '/export',
      summary: 'Export transfers to CSV',
      permissions: permissions.inventory.transferView,
      raw: true,
      handler: async (req: any, reply: any) => {
        const { limit, ...filters } = req.query;
        const exportLimit = Math.min(parseInt(limit, 10) || 10000, 50000);
        const result = await transferService.listTransfers(filters, {
          limit: exportLimit,
          sort: '-createdAt',
          populate: true,
        });

        const csvRows: string[] = [
          'Transfer ID,Number,Type,Status,Sender,Receiver,Items,Quantity,Value,Created,Dispatched,Received',
        ];
        for (const t of (result.docs || []) as any[]) {
          const sender = typeof t.senderBranch === 'object' ? t.senderBranch?.name : t.senderBranch;
          const receiver = typeof t.receiverBranch === 'object' ? t.receiverBranch?.name : t.receiverBranch;
          csvRows.push(
            [
              t._id,
              t.documentNumber || '',
              t.transferType || '',
              t.status || '',
              sender || '',
              receiver || '',
              t.totalItems || 0,
              t.totalQuantity || 0,
              t.totalValue || 0,
              t.createdAt ? new Date(t.createdAt).toISOString() : '',
              t.dispatchedAt ? new Date(t.dispatchedAt).toISOString() : '',
              t.receivedAt ? new Date(t.receivedAt).toISOString() : '',
            ].join(','),
          );
        }

        reply.header('Content-Type', 'text/csv');
        reply.header(
          'Content-Disposition',
          `attachment; filename="transfers-${new Date().toISOString().split('T')[0]}.csv"`,
        );
        reply.send(csvRows.join('\n'));
      },
    },
  ],
});

export default transferResource;
