export const ORDER_STATUS = {
  PENDING: 'pending',
  PROCESSING: 'processing',
  CONFIRMED: 'confirmed',
  SHIPPED: 'shipped',
  DELIVERED: 'delivered',
  CANCELLED: 'cancelled',
};

export const PAYMENT_STATUS = {
  PENDING: 'pending',
  VERIFIED: 'verified',
  FAILED: 'failed',
  REFUNDED: 'refunded',
  PARTIALLY_REFUNDED: 'partially_refunded',
  CANCELLED: 'cancelled',
};

export const STATUS_TRANSITIONS = {
  [ORDER_STATUS.PENDING]: [ORDER_STATUS.PROCESSING, ORDER_STATUS.CONFIRMED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.PROCESSING]: [ORDER_STATUS.CONFIRMED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.CONFIRMED]: [ORDER_STATUS.SHIPPED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.SHIPPED]: [ORDER_STATUS.DELIVERED],
  [ORDER_STATUS.DELIVERED]: [],
  [ORDER_STATUS.CANCELLED]: [],
};

export const PAYMENT_METHODS = {
  CASH: 'cash',
  BKASH: 'bkash',
  NAGAD: 'nagad',
  ROCKET: 'rocket',
  BANK_TRANSFER: 'bank_transfer',
};

export const SHIPPING_PROVIDER = {
  REDX: 'redx',
  PATHAO: 'pathao',
  STEADFAST: 'steadfast',
  PAPERFLY: 'paperfly',
  SUNDARBAN: 'sundarban',
  SA_PARIBAHAN: 'sa_paribahan',
  DHL: 'dhl',
  FEDEX: 'fedex',
  OTHER: 'other',
};

export const SHIPPING_STATUS = {
  PENDING: 'pending',
  REQUESTED: 'requested',
  PICKED_UP: 'picked_up',
  IN_TRANSIT: 'in_transit',
  OUT_FOR_DELIVERY: 'out_for_delivery',
  DELIVERED: 'delivered',
  FAILED_ATTEMPT: 'failed_attempt',
  RETURNED: 'returned',
  CANCELLED: 'cancelled',
};

export const SHIPPING_STATUS_TRANSITIONS = {
  [SHIPPING_STATUS.PENDING]: [SHIPPING_STATUS.REQUESTED, SHIPPING_STATUS.CANCELLED],
  [SHIPPING_STATUS.REQUESTED]: [SHIPPING_STATUS.PICKED_UP, SHIPPING_STATUS.CANCELLED],
  [SHIPPING_STATUS.PICKED_UP]: [SHIPPING_STATUS.IN_TRANSIT, SHIPPING_STATUS.RETURNED],
  [SHIPPING_STATUS.IN_TRANSIT]: [SHIPPING_STATUS.OUT_FOR_DELIVERY, SHIPPING_STATUS.RETURNED],
  [SHIPPING_STATUS.OUT_FOR_DELIVERY]: [SHIPPING_STATUS.DELIVERED, SHIPPING_STATUS.FAILED_ATTEMPT],
  [SHIPPING_STATUS.FAILED_ATTEMPT]: [SHIPPING_STATUS.OUT_FOR_DELIVERY, SHIPPING_STATUS.RETURNED],
  [SHIPPING_STATUS.DELIVERED]: [],
  [SHIPPING_STATUS.RETURNED]: [],
  [SHIPPING_STATUS.CANCELLED]: [],
};

export const SHIPPING_TO_ORDER_STATUS_MAP = {
  [SHIPPING_STATUS.PICKED_UP]: ORDER_STATUS.SHIPPED,
  [SHIPPING_STATUS.IN_TRANSIT]: ORDER_STATUS.SHIPPED,
  [SHIPPING_STATUS.OUT_FOR_DELIVERY]: ORDER_STATUS.SHIPPED,
  [SHIPPING_STATUS.DELIVERED]: ORDER_STATUS.DELIVERED,
};

export default {
  ORDER_STATUS,
  PAYMENT_STATUS,
  STATUS_TRANSITIONS,
  PAYMENT_METHODS,
  SHIPPING_PROVIDER,
  SHIPPING_STATUS,
  SHIPPING_STATUS_TRANSITIONS,
  SHIPPING_TO_ORDER_STATUS_MAP,
};

