/**
 * Purchase Resource — Arc CRUD + Stripe Actions
 *
 * CRUD (list, get, create, update, delete) auto-generated by Arc's BaseController.
 * State transitions (receive/pay/cancel) declared via the `actions` block below
 * → mounted as `POST /:id/action { action: "receive" | "pay" | "cancel" }`.
 */
import { createMongooseAdapter, defineResource } from '@classytic/arc';
import { requireRoles } from '@classytic/arc/permissions';
import { QueryParser } from '@classytic/mongokit';
import permissions from '#config/permissions.js';
import PurchaseOrder from './models/purchase-order.model.js';
import purchaseOrderController from './purchase-order.controller.js';
import purchaseOrderRepository from './purchase-order.repository.js';
import { cancelActionSchema, createSchema, payActionSchema, updateSchema } from './purchase-order.schemas.js';
import purchaseOrderService from './purchase-order.service.js';

const queryParser = new QueryParser({
  maxLimit: 100,
  allowedFilterFields: ['status', 'paymentStatus', 'branch', 'supplier', 'paymentTerms'],
  allowedSortFields: ['createdAt', 'updatedAt', 'invoiceDate', 'dueDate', 'grandTotal', 'invoiceNumber'],
});

const purchaseOrderResource = defineResource({
  name: 'purchase-order',
  audit: true,
  displayName: 'Purchase Orders',
  tag: 'Inventory - Purchase Orders',
  prefix: '/inventory/purchase-orders',

  adapter: createMongooseAdapter(PurchaseOrder, purchaseOrderRepository),
  queryParser,
  // Custom controller: create/update go through purchaseOrderService
  // (item normalization, supplier lookup, total computation, invoice numbering).
  // Arc's BaseController handles list/get/delete via the adapter.
  controller: purchaseOrderController,

  permissions: {
    list: permissions.inventory.purchaseOrderView,
    get: permissions.inventory.purchaseOrderView,
    create: permissions.inventory.purchaseOrder,
    update: permissions.inventory.purchaseOrder,
    delete: requireRoles('admin'),
  },

  // Zod v4 bodies — Arc auto-converts to JSON Schema at registration. The
  // service still does normalization (supplier lookup, totals, invoice
  // numbering), but invalid bodies fail at the gateway with a structured
  // error rather than slipping through to a `createStatusError` deep in
  // the service.
  customSchemas: {
    create: { body: createSchema.body },
    update: { body: updateSchema.body },
  },

  actions: {
    receive: {
      handler: async (id, _data, req) => {
        const uid = String(req.user?._id || req.user?.id || '');
        return purchaseOrderService.receivePurchase(id, uid);
      },
      permissions: permissions.inventory.purchaseOrderReceive,
    },
    pay: {
      handler: async (id, data, req) => {
        const uid = String(req.user?._id || req.user?.id || '');
        return purchaseOrderService.payPurchase(id, data, uid);
      },
      permissions: permissions.inventory.purchaseOrderPay,
      schema: payActionSchema,
    },
    cancel: {
      handler: async (id, data, req) => {
        const uid = String(req.user?._id || req.user?.id || '');
        return purchaseOrderService.cancelPurchase(id, uid, data.reason as string | undefined);
      },
      permissions: permissions.inventory.purchaseOrderCancel,
      schema: cancelActionSchema,
    },
  },
});

export default purchaseOrderResource;
