/**
 * Purchase Resource — Arc CRUD + Stripe Actions
 *
 * CRUD (list, get, create, update, delete) auto-generated by Arc's BaseController.
 * State transitions (receive/pay/cancel) declared via the `actions` block below
 * → mounted as `POST /:id/action { action: "receive" | "pay" | "cancel" }`.
 */
import { defineResource } from '@classytic/arc';
import { requireRoles } from '@classytic/arc/permissions';
import { QueryParser } from '@classytic/mongokit';
import permissions from '#config/permissions.js';
import { createAdapter } from '#shared/adapter.js';
import PurchaseOrder from './models/purchase-order.model.js';
import purchaseOrderController from './purchase-order.controller.js';
import purchaseOrderRepository from './purchase-order.repository.js';
import purchaseOrderService from './purchase-order.service.js';

const queryParser = new QueryParser({
  maxLimit: 100,
  allowedFilterFields: ['status', 'paymentStatus', 'branch', 'supplier', 'paymentTerms'],
  allowedSortFields: ['createdAt', 'updatedAt', 'invoiceDate', 'dueDate', 'grandTotal', 'invoiceNumber'],
});

const purchaseOrderResource = defineResource({
  name: 'purchase-order',
  audit: true,
  displayName: 'Purchase Orders',
  tag: 'Inventory - Purchase Orders',
  prefix: '/inventory/purchase-orders',

  adapter: createAdapter(PurchaseOrder, purchaseOrderRepository),
  queryParser,
  // Custom controller: create/update go through purchaseOrderService
  // (item normalization, supplier lookup, total computation, invoice numbering).
  // Arc's BaseController handles list/get/delete via the adapter.
  controller: purchaseOrderController,

  permissions: {
    list: permissions.inventory.purchaseOrderView,
    get: permissions.inventory.purchaseOrderView,
    create: permissions.inventory.purchaseOrder,
    update: permissions.inventory.purchaseOrder,
    delete: requireRoles('admin'),
  },

  // Tight schemas matching the create / update payload contracts. The service
  // still does normalization (supplier lookup, totals, invoice numbering),
  // but invalid bodies fail at the gateway with a structured error rather
  // than slipping through to a `createStatusError` deep in the service. Lines
  // and payment substructure are validated as well.
  customSchemas: {
    create: {
      body: {
        type: 'object',
        required: ['items'],
        additionalProperties: false,
        properties: {
          supplierId: { type: 'string' },
          branchId: { type: 'string' },
          purchaseOrderNumber: { type: 'string' },
          invoiceDate: { type: 'string', format: 'date-time' },
          paymentTerms: { type: 'string', enum: ['cash', 'credit'] },
          creditDays: { type: 'number', minimum: 0 },
          dueDate: { type: 'string', format: 'date-time' },
          notes: { type: 'string' },
          autoApprove: { type: 'boolean' },
          autoReceive: { type: 'boolean' },
          items: {
            type: 'array',
            minItems: 1,
            items: {
              type: 'object',
              required: ['productId'],
              additionalProperties: false,
              properties: {
                productId: { type: 'string' },
                variantSku: { type: ['string', 'null'] },
                quantity: { type: 'number', minimum: 0 },
                costPrice: { type: 'number', minimum: 0 },
                discount: { type: 'number', minimum: 0 },
                taxRate: { type: 'number', minimum: 0, maximum: 100 },
                notes: { type: 'string' },
                destinationLocationId: { type: 'string' },
              },
            },
          },
          payment: {
            type: 'object',
            additionalProperties: false,
            properties: {
              amount: { type: 'number', minimum: 0 },
              method: { type: 'string' },
              reference: { type: 'string' },
              accountNumber: { type: 'string' },
              walletNumber: { type: 'string' },
              bankName: { type: 'string' },
              accountName: { type: 'string' },
              proofUrl: { type: 'string' },
              transactionDate: { type: 'string', format: 'date-time' },
              notes: { type: 'string' },
            },
          },
        },
      },
    },
    update: {
      body: {
        type: 'object',
        additionalProperties: false,
        properties: {
          supplierId: { type: 'string' },
          purchaseOrderNumber: { type: 'string' },
          invoiceDate: { type: 'string', format: 'date-time' },
          paymentTerms: { type: 'string', enum: ['cash', 'credit'] },
          creditDays: { type: 'number', minimum: 0 },
          dueDate: { type: 'string', format: 'date-time' },
          notes: { type: 'string' },
          items: {
            type: 'array',
            items: {
              type: 'object',
              required: ['productId'],
              additionalProperties: false,
              properties: {
                productId: { type: 'string' },
                variantSku: { type: ['string', 'null'] },
                quantity: { type: 'number', minimum: 0 },
                costPrice: { type: 'number', minimum: 0 },
                discount: { type: 'number', minimum: 0 },
                taxRate: { type: 'number', minimum: 0, maximum: 100 },
                notes: { type: 'string' },
                destinationLocationId: { type: 'string' },
              },
            },
          },
        },
      },
    },
  },

  schemaOptions: {
    fieldRules: {
      invoiceNumber: { systemManaged: true },
      status: { systemManaged: true },
      paymentStatus: { systemManaged: true },
      paidAmount: { systemManaged: true },
      dueAmount: { systemManaged: true },
      subTotal: { systemManaged: true },
      discountTotal: { systemManaged: true },
      taxTotal: { systemManaged: true },
      grandTotal: { systemManaged: true },
      statusHistory: { systemManaged: true },
      createdBy: { systemManaged: true },
      approvedBy: { systemManaged: true },
      receivedBy: { systemManaged: true },
    },
  },

  actions: {
    receive: {
      handler: async (id, _data, req) => {
        const uid = String(req.user?._id || req.user?.id || '');
        return purchaseOrderService.receivePurchase(id, uid);
      },
      permissions: permissions.inventory.purchaseOrderReceive,
    },
    pay: {
      handler: async (id, data, req) => {
        const uid = String(req.user?._id || req.user?.id || '');
        return purchaseOrderService.payPurchase(id, data, uid);
      },
      permissions: permissions.inventory.purchaseOrderPay,
      schema: {
        amount: { type: 'number', description: 'Payment amount (BDT)' },
        method: { type: 'string', description: 'Payment method' },
        reference: { type: 'string', description: 'Payment reference' },
        accountNumber: { type: 'string' },
        walletNumber: { type: 'string' },
        bankName: { type: 'string' },
        accountName: { type: 'string' },
        proofUrl: { type: 'string' },
        transactionDate: { type: 'string', format: 'date-time' },
        notes: { type: 'string' },
      },
    },
    cancel: {
      handler: async (id, data, req) => {
        const uid = String(req.user?._id || req.user?.id || '');
        return purchaseOrderService.cancelPurchase(id, uid, data.reason as string | undefined);
      },
      permissions: permissions.inventory.purchaseOrderCancel,
      schema: { reason: { type: 'string', description: 'Cancellation reason' } },
    },
  },
});

export default purchaseOrderResource;
