/**
 * Purchase Resource — Arc CRUD + Stripe Actions
 *
 * CRUD (list, get, create, update, delete) auto-generated by Arc's BaseController.
 * State transitions (approve/receive/pay/cancel) declared via the `actions` block
 * → mounted as `POST /:id/action { action: "approve" | "receive" | ... }`.
 *
 * Approval chain: this resource opts into the unified approval framework via
 * `withApprovalChain` (`#core/approval`). The preset contributes
 * `submit_for_approval` + `decide`; the existing `approve` action stays as the
 * terminal lifecycle verb (draft → approved) and gates on
 * `isApproved(doc.approvals)` when a chain is attached. Without a chain, the
 * SME path runs — direct flip via the existing `approvePurchase()` helper.
 *
 * Subject type is `purchase_order_internal` (NOT `purchase_order` — that one
 * is owned by Flow's procurement subject; we run a parallel pipeline here for
 * be-prod's own simpler PO model and don't share approval policies).
 */
import { defineResource } from '@classytic/arc';
import { createMongooseAdapter } from '@classytic/mongokit/adapter';
import { requireRoles } from '@classytic/arc/permissions';
import { QueryParser } from '@classytic/mongokit';
import type { Repository } from '@classytic/mongokit';
import { isApproved } from '@classytic/primitives/approval';
import { createDomainError } from '@classytic/arc/utils';
import permissions from '#config/permissions.js';
import {
  withApprovalChain,
  type ApprovableDoc,
} from '#core/approval/with-approval-chain.js';
import { createPolicyChainResolver } from '#resources/approval/policy-resolver.js';
import { buildPurchaseCtx } from '#resources/inventory/_engines/ctx.js';
import { getPurchaseEngine } from '#resources/inventory/_engines/purchase.engine.js';
import purchaseOrderService from './purchase-order.service.js';
import purchaseOrderController from './purchase-order.controller.js';
import purchaseOrderRepository from './purchase-order.repository.js';
import { cancelActionSchema, createSchema, payActionSchema, updateSchema } from './purchase-order.schemas.js';
import { normalizeNumber } from './purchase-order.utils.js';

const queryParser = new QueryParser({
  maxLimit: 100,
  allowedFilterFields: ['status', 'paymentStatus', 'branch', 'supplier', 'paymentTerms'],
  allowedSortFields: ['createdAt', 'updatedAt', 'invoiceDate', 'dueDate', 'grandTotal', 'invoiceNumber'],
});

/**
 * Local typed view of a PurchaseOrder document for the approval preset. The
 * preset reads `_id` and `approvals` only; we surface the few extra fields the
 * `toEvaluationContext` callback needs (branch, supplier, items totals).
 */
interface PurchaseOrderDoc extends ApprovableDoc {
  status: string;
  branch?: unknown;
  supplier?: unknown;
  grandTotal?: number;
  items?: Array<{ quantity?: number; costPrice?: number }>;
}

const approvalActions = withApprovalChain<PurchaseOrderDoc>({
  // Distinct from Flow's `purchase_order` subject (procurement.factory.ts) so
  // the matrix policy resource can target this be-prod PO independently.
  subjectType: 'purchase_order_internal',
  // mongokit's `Repository<IPurchaseOrder>` types `_id` more loosely than
  // `ApprovableDoc.readonly _id: unknown`. One `as unknown as` cast at the
  // package boundary — same shape budget.actions.ts uses.
  repository: purchaseOrderRepository as unknown as Repository<PurchaseOrderDoc>,
  // 'cancelled'/'received' are terminal — only draft PO can enter the chain.
  allowedSubmitStatus: ['draft'],
  permissions: {
    submit: permissions.inventory.purchaseOrder,
    decide: permissions.inventory.purchaseOrder,
  },
  toEvaluationContext: (po) => {
    // Threshold matrices key on order amount. Prefer the persisted
    // `grandTotal`; fall back to a fresh sum if it's missing (very early
    // drafts, edge cases).
    const persisted = normalizeNumber(po.grandTotal, 0);
    const amount = persisted > 0
      ? persisted
      : (po.items ?? []).reduce(
          (sum, item) => sum + normalizeNumber(item.quantity, 0) * normalizeNumber(item.costPrice, 0),
          0,
        );
    return {
      branchId: String(po.branch ?? ''),
      amount,
      ...(po.supplier ? { supplierId: String(po.supplier) } : {}),
    };
  },
  resolveChain: createPolicyChainResolver(),
});

export function createPurchaseOrderResource() {
  return defineResource({
  name: 'purchase-order',
  audit: true,
  displayName: 'Purchase Orders',
  tag: 'Inventory - Purchase Orders',
  prefix: '/inventory/purchase-orders',

  adapter: createMongooseAdapter(getPurchaseEngine().models.PurchaseOrder, purchaseOrderRepository),
  queryParser,
  tenantField: false,
  // Custom controller: create/update go through purchaseOrderService
  // (item normalization, supplier lookup, total computation, invoice numbering).
  // Arc's BaseController handles list/get/delete via the adapter.
  controller: purchaseOrderController,

  permissions: {
    list: permissions.inventory.purchaseOrderView,
    get: permissions.inventory.purchaseOrderView,
    create: permissions.inventory.purchaseOrder,
    update: permissions.inventory.purchaseOrder,
    delete: requireRoles('admin'),
  },

  // Zod v4 bodies — Arc auto-converts to JSON Schema at registration. The
  // service still does normalization (supplier lookup, totals, invoice
  // numbering), but invalid bodies fail at the gateway with a structured
  // error rather than slipping through to a `createStatusError` deep in
  // the service.
  customSchemas: {
    create: { body: createSchema.body },
    update: { body: updateSchema.body },
  },

  actions: {
    ...approvalActions,

    approve: {
      handler: async (id, _data, req) => {
        const { actorId } = buildPurchaseCtx(req);
        // Chain gate: if an approval chain exists it must reach `approved`
        // before the terminal approve fires. Without a chain → SME path.
        const current = (await purchaseOrderRepository.getById(id, { lean: true })) as PurchaseOrderDoc | null;
        if (current?.approvals && !isApproved(current.approvals)) {
          throw createDomainError(
            'approval.chain_incomplete',
            'Approval chain has not reached `approved` — cannot finalize PO approval.',
            422,
          );
        }
        return purchaseOrderService.approvePurchase(id, actorId || undefined);
      },
      permissions: permissions.inventory.purchaseOrder,
    },

    receive: {
      handler: async (id, _data, req) => {
        const { actorId } = buildPurchaseCtx(req);
        return purchaseOrderService.receivePurchase(id, actorId || undefined);
      },
      permissions: permissions.inventory.purchaseOrderReceive,
    },

    pay: {
      handler: async (id, data, req) => {
        const { actorId } = buildPurchaseCtx(req);
        return purchaseOrderService.payPurchase(
          id,
          {
            amount: data.amount as number,
            method: data.method as string | undefined,
            reference: (data.reference ?? data.transactionId) as string | undefined,
          },
          actorId || undefined,
        );
      },
      permissions: permissions.inventory.purchaseOrderPay,
      schema: payActionSchema,
    },

    cancel: {
      handler: async (id, data, req) => {
        const { actorId } = buildPurchaseCtx(req);
        return purchaseOrderService.cancelPurchase(id, actorId || undefined, data.reason as string | undefined);
      },
      permissions: permissions.inventory.purchaseOrderCancel,
      schema: cancelActionSchema,
    },
  },
  });
}
