/**
 * Stock Audit Resource — cycle-count sessions.
 *
 * Delegates to Flow's counting service. Supports full / cycle / spot
 * audits with freeze policies. Variance + reconciliation routes turn
 * counted-vs-expected into adjustment moves.
 *
 * Mirrors the scrap / return-order template:
 *   - `adapter` for read CRUD (list/get)
 *   - `StockAuditController` override for `create` → `counting.createSession`
 *   - Custom `routes:` for `/:id/lines` (POST payload) and `/:id/variance`
 *     (derived report — no persistence)
 *   - `actions:` for `reconcile` and `post-moves` FSM verbs
 *   - `disabledRoutes: ['update']`
 *
 * No mode gate — stock audits work on all FLOW_MODE tiers.
 */

import { defineResource, BaseController } from '@classytic/arc';
import type { IRequestContext, IControllerResponse } from '@classytic/arc';
import { QueryParser, type Repository } from '@classytic/mongokit';
import { isApproved } from '@classytic/primitives/approval';
import type { FastifyReply, FastifyRequest } from 'fastify';
import permissions from '#config/permissions.js';
import {
  withApprovalChain,
  type ApprovableDoc,
} from '#core/approval/with-approval-chain.js';
import { createPolicyChainResolver } from '#resources/approval/policy-resolver.js';
import { createFlowAdapter } from '#shared/flow-adapter.js';
import { createDomainError } from '@classytic/arc/utils';
import { flow, flowCtxFromArcReq, flowCtxGuard } from '../shared/helpers.js';

/**
 * Local typed view of an InventoryCount document. Extends `ApprovableDoc`
 * so the preset reads `doc.approvals` natively (P7 — flow ≥ today bakes
 * `approvals?: ApprovalChain` into the InventoryCount schema).
 */
interface StockAuditDoc extends ApprovableDoc {
  organizationId?: string;
  countNumber?: string;
  countType?: 'full' | 'cycle' | 'spot';
  status: string;
  scope?: { nodeId?: string; locationId?: string; skuRefs?: string[] };
}

interface CreateCountSessionBody {
  countType: 'full' | 'cycle' | 'spot';
  scope?: { nodeId?: string; locationId?: string; skuRefs?: string[] };
  freezePolicy?: 'hard_freeze' | 'soft_freeze' | 'none';
}

class StockAuditController extends BaseController {
  async create(req: IRequestContext): Promise<IControllerResponse<Record<string, unknown>>> {
    const ctx = flowCtxFromArcReq(req);
    const body = req.body as CreateCountSessionBody;
    const session = await flow().services.counting.createSession(
      {
        countType: body.countType,
        scope: body.scope ?? {},
        freezePolicy: body.freezePolicy,
      },
      ctx,
    );
    return { data: session as unknown as Record<string, unknown>, status: 201 };
  }
}

export function createStockAuditResource() {
  const engine = flow();

  return defineResource({
    name: 'stock-audit',
    displayName: 'Stock Audits',
    tag: 'Warehouse - Audit',
    prefix: '/inventory/audits',

    adapter: createFlowAdapter(engine.models.InventoryCount, engine.repositories.count, {
      // Server-assigned: countNumber (generated by service), status/freezePolicy
      // (have defaults but mongoose marks required), and lifecycle timestamps.
      fieldRules: {
        organizationId: { systemManaged: true },
        countNumber: { systemManaged: true },
        status: { systemManaged: true },
        startedAt: { systemManaged: true },
        submittedAt: { systemManaged: true },
        reconciledAt: { systemManaged: true },
        createdBy: { systemManaged: true },
        modifiedBy: { systemManaged: true },
        approvedBy: { systemManaged: true },
        // Mutated only via submit_for_approval / decide actions; never via PATCH.
        approvals: { systemManaged: true },
        approvalPolicyId: { systemManaged: true },
        approvalPolicyVersion: { systemManaged: true },
      },
    }),

    controller: new StockAuditController(engine.repositories.count),
    disabledRoutes: ['update'],

    queryParser: new QueryParser({
      maxLimit: 100,
      allowedFilterFields: ['status', 'countType', 'freezePolicy'],
    }),

    permissions: {
      list: permissions.inventory.view,
      get: permissions.inventory.view,
      create: permissions.inventory.adjust,
      update: permissions.inventory.adjust, // ignored (route disabled) but kept for type
      delete: permissions.inventory.adjust,
    },

    routes: [
      {
        method: 'POST',
        path: '/:id/lines',
        summary: 'Submit count lines',
        description:
          'Submit counted quantities for locations/SKUs. Supports bulk submission from mobile scan.',
        permissions: permissions.inventory.adjust,
        raw: true,
        preHandler: [flowCtxGuard.preHandler],
        handler: async (req: FastifyRequest, reply: FastifyReply) => {
          const { id } = req.params as { id: string };
          const ctx = flowCtxGuard.from(req);
          const { lines } = req.body as {
            lines: Array<{
              skuRef: string;
              locationId: string;
              lotId?: string;
              serialCode?: string;
              countedQuantity: number;
              varianceReason?: string;
            }>;
          };
          const result = await flow().services.counting.submitLines(id, lines, ctx);
          return reply.send({ data: result });
        },
      },
      {
        method: 'GET',
        path: '/:id/variance',
        summary: 'Get variance report',
        description:
          'Compare counted vs expected quantities. Shows per-bin discrepancies.',
        permissions: permissions.inventory.view,
        raw: true,
        preHandler: [flowCtxGuard.preHandler],
        handler: async (req: FastifyRequest, reply: FastifyReply) => {
          const { id } = req.params as { id: string };
          const ctx = flowCtxGuard.from(req);
          const variance = await flow().services.counting.calculateVariance(id, ctx);
          return reply.send({ data: variance });
        },
      },
    ],

    actions: {
      // Chain workflow — submit_for_approval + decide come from the shared
      // preset. Only `submitted` audits may enter the approval pipeline
      // (counters submit lines first; THEN a supervisor reviews variance
      // and approves before reconciliation moves are posted). For the
      // simple SME path with no chain attached, `reconcile` runs directly.
      ...withApprovalChain<StockAuditDoc>({
        subjectType: 'stock_audit',
        repository: engine.repositories.count as unknown as Repository<StockAuditDoc>,
        allowedSubmitStatus: ['submitted'],
        permissions: {
          submit: permissions.inventory.adjust,
          decide: permissions.inventory.adjust,
        },
        toEvaluationContext: (doc) => ({
          branchId: String(doc.organizationId ?? ''),
          ...(doc.countType ? { countType: doc.countType } : {}),
        }),
        resolveChain: createPolicyChainResolver(),
        // No status flips here — `reconcile` is the terminal action that
        // moves status forward. The chain just gates whether reconcile
        // can run (see the gate in the action handler below).
      }),

      reconcile: {
        handler: async (id, data, req) => {
          const ctx = flowCtxFromArcReq(req as unknown as IRequestContext);
          // Chain gate (P7) — when an audit has an attached approval chain
          // it must be approved before reconciliation moves are posted.
          // SME path with no chain attached runs through unchanged.
          const doc = (await engine.repositories.count.getById(id, {
            organizationId: ctx.organizationId,
            throwOnNotFound: false,
            lean: true,
          })) as StockAuditDoc | null;
          if (doc?.approvals && !isApproved(doc.approvals)) {
            throw createDomainError(
              'approval.chain_incomplete',
              `Cannot reconcile audit while approval chain is ${doc.approvals.status}.`,
              422,
            );
          }
          return engine.services.counting.reconcile(
            id,
            { autoApproveThreshold: (data as { autoApproveThreshold?: number }).autoApproveThreshold },
            ctx,
          );
        },
        permissions: permissions.inventory.adjust,
      },
      'post-moves': {
        handler: async (id, _data, req) => {
          const ctx = flowCtxFromArcReq(req as unknown as IRequestContext);
          await engine.services.counting.postReconciliationMoves(id, ctx);
          return { posted: true };
        },
        permissions: permissions.inventory.adjust,
      },
    },
  });
}
