/**
 * Invoice E2E Integration Tests
 *
 * Full HTTP-level tests via Fastify inject. Uses the same app boot +
 * Better Auth setup as accounting-e2e.test.ts.
 *
 * Covers:
 *   1. CRUD via Arc adapter (GET /, GET /:id, POST /, PATCH /:id)
 *   2. Action router (POST /:id/action — post, cancel, record_payment, credit_note)
 *   3. Custom routes (aging, overdue, receipt, document data)
 *   4. Streamline workflow listing
 *   5. QueryParser filtering (?status=draft&moveType=out_invoice)
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest'; import mongoose from 'mongoose'; import { setupBetterAuthTestApp } from '@classytic/arc/testing';
import { createBetterAuthProvider, type TestAuthProvider } from '@classytic/arc/testing';
import type { FastifyInstance } from 'fastify';

let ctx;
let auth: TestAuthProvider;
let server: FastifyInstance;
const API = '/api/v1';

function parse(body: string) {
  try { return JSON.parse(body); } catch { return null; }
}

async function seedPlatformConfig(): Promise<void> {
  const db = mongoose.connection.db;
  if (!db) return;
  const col = db.collection('platformconfigs');
  const existing = await col.findOne({ isSingleton: true });
  if (!existing) {
    await col.insertOne({
      isSingleton: true, storeName: 'Invoice Test', currency: 'BDT',
      membership: { enabled: false }, createdAt: new Date(), updatedAt: new Date(),
    });
  }
}

beforeAll(async () => {
  process.env.JWT_SECRET = 'test-secret-key-1234567890-abcdefgh';
  process.env.JWT_REFRESH_SECRET = 'test-refresh-secret-1234567890-xyz';
  process.env.COOKIE_SECRET = 'test-cookie-secret-key-1234567890123456';
  process.env.NODE_ENV = 'test';
  process.env.ENABLE_ACCOUNTING = 'true';
  process.env.ACCOUNTING_MODE = 'standard';
  process.env.INVOICE_ENGINE = 'true';
  process.env.STREAMLINE_ENABLED = 'true';

  if ((globalThis as any).__MONGO_URI__) {
    process.env.MONGO_URI = (globalThis as any).__MONGO_URI__;
  }

  if (mongoose.connection.readyState !== 1) {
    await mongoose.connect(process.env.MONGO_URI!);
  }
  await seedPlatformConfig();

  const { createApplication } = await import('../../../src/app.js');
  const { loadTestResources } = await import('../../support/preload-resources.js');
  const { resources: __preloaded } = await loadTestResources();
  const { getAuth } = await import('../../../src/resources/auth/auth.config.js');

    const __testApp = await createApplication({ resources: __preloaded });
ctx = await setupBetterAuthTestApp({
    app: __testApp,
    org: { name: `Invoice-${Date.now()}`, slug: `inv-${Date.now()}` },
    users: [
      { key: 'admin', email: `inv-admin-${Date.now()}@test.com`, password: 'TestPass123!', name: 'Admin', role: 'admin', isCreator: true },
    ],
    addMember: async (data) => {
      const res = await getAuth().api.addMember({ body: { organizationId: data.organizationId ?? data.orgId, userId: data.userId, role: data.role } });
      return { statusCode: res ? 200 : 500, body: '' };
    },
  });

  server = ctx.app;
  auth = createBetterAuthProvider({ defaultOrgId: ctx.orgId });
  auth.register('admin', { token: ctx.users.admin.token });

  // Set platform admin role
  await mongoose.connection.db!.collection('user').updateOne(
    { email: ctx.users.admin.email },
    { $set: { role: ['admin'] } },
  );

  // Seed chart of accounts (needed for ledger bridge)
  await server.inject({
    method: 'POST', url: `${API}/accounting/accounts/seed`, headers: h(),
  });
}, 60_000);

afterAll(async () => {
  if (ctx?.teardown) await ctx.teardown();
}, 30_000);

function h() { return auth.as('admin').headers; }

// ── 1. CRUD (auto-generated by Arc adapter) ─────────────────────────────────

describe('Invoice CRUD', () => {
  let invoiceId: string;

  it('POST / — creates a draft invoice', async () => {
    const res = await server.inject({
      method: 'POST',
      url: `${API}/accounting/invoices`,
      headers: h(),
      // Minimal payload: omits `currency` (engine defaults from `deps.currency`)
      // and `lines[].sequence` (auto-assigned by the pre-validate hook). Both
      // are declared optional at the Arc schema layer so a realistic client
      // isn't forced to echo them.
      payload: {
        moveType: 'out_invoice',
        partnerId: 'test-customer-001',
        partnerName: 'Test Corp',
        lines: [
          { description: 'Widget A', quantity: 10, unitPrice: 500 },
          { description: 'Service B', quantity: 2, unitPrice: 2500 },
        ],
      },
    });

    expect([200, 201]).toContain(res.statusCode);
    const body = parse(res.body);
    expect(body.status).toBe('draft');
    expect(body.moveType).toBe('out_invoice');
    invoiceId = body._id;
  });

  it('GET / — lists invoices with QueryParser filters', async () => {
    const res = await server.inject({
      method: 'GET',
      url: `${API}/accounting/invoices?status=draft&moveType=out_invoice`,
      headers: h(),
    });

    expect(res.statusCode).toBe(200);
    const body = parse(res.body);
    // Arc's list envelope spreads MongoKit's OffsetPaginationResult directly —
    // `docs` is at the root, not under `data` (same shape as /payment-terms
    // below). Asserting on the root shape guards the contract the SDK reads.
    expect(Array.isArray(body.data)).toBe(true);
    expect(body.data.length).toBeGreaterThanOrEqual(1);
  });

  it('GET /:id — gets invoice by ID', async () => {
    const res = await server.inject({
      method: 'GET',
      url: `${API}/accounting/invoices/${invoiceId}`,
      headers: h(),
    });

    expect(res.statusCode).toBe(200);
    const body = parse(res.body);
    expect(body.partnerId).toBe('test-customer-001');
  });

  it('PATCH /:id — updates draft invoice', async () => {
    const res = await server.inject({
      method: 'PATCH',
      url: `${API}/accounting/invoices/${invoiceId}`,
      headers: h(),
      payload: { notes: 'Updated via E2E test' },
    });

    expect(res.statusCode).toBe(200);
    const body = parse(res.body);
  });
});

// ── 2. Action Router (post, cancel, record_payment) ─────────────────────────

describe('Invoice Actions', () => {
  let invoiceId: string;

  beforeAll(async () => {
    const res = await server.inject({
      method: 'POST',
      url: `${API}/accounting/invoices`,
      headers: h(),
      payload: {
        moveType: 'out_invoice',
        partnerId: 'action-test-customer',
        lines: [{ description: 'Test Item', quantity: 1, unitPrice: 10000 }],
      },
    });
    invoiceId = parse(res.body)._id;
  });

  it('POST /:id/action { action: "post" } — posts invoice', async () => {
    const res = await server.inject({
      method: 'POST',
      url: `${API}/accounting/invoices/${invoiceId}/action`,
      headers: h(),
      payload: { action: 'post' },
    });

    expect(res.statusCode).toBe(200);
    const body = parse(res.body);
    expect(body.status).toBe('posted');
    expect(body.number).toBeTruthy();
  });

  it('POST /:id/action { action: "record_payment" } — records payment', async () => {
    const inv = parse((await server.inject({
      method: 'GET', url: `${API}/accounting/invoices/${invoiceId}`, headers: h(),
    })).body);

    const res = await server.inject({
      method: 'POST',
      url: `${API}/accounting/invoices/${invoiceId}/action`,
      headers: h(),
      payload: {
        action: 'record_payment',
        paymentId: `pay-e2e-${Date.now()}`,
        amount: inv.totalAmount,
        method: 'bank_transfer',
      },
    });

    expect(res.statusCode).toBe(200);
    const body = parse(res.body);
  });
});

// ── 3. Custom Routes ────────────────────────────────────────────────────────

describe('Custom Invoice Routes', () => {
  it('GET /aging — returns aging report', async () => {
    const res = await server.inject({
      method: 'GET',
      url: `${API}/accounting/invoices/aging?side=receivable`,
      headers: h(),
    });

    expect(res.statusCode).toBe(200);
    const body = parse(res.body);
    expect(body.buckets).toBeTruthy();
  });

  it('GET /overdue — returns overdue list', async () => {
    const res = await server.inject({
      method: 'GET',
      url: `${API}/accounting/invoices/overdue`,
      headers: h(),
    });

    expect(res.statusCode).toBe(200);
    const body = parse(res.body);
  });

  it('GET /payment-terms — returns flattened paginated response', async () => {
    const res = await server.inject({
      method: 'GET',
      url: `${API}/accounting/payment-terms`,
      headers: h(),
    });

    expect(res.statusCode).toBe(200);
    const body = parse(res.body);
    // Arc 2.13: paginated list emits flat
    // `{ method: 'offset', data: [...], page, limit, total, pages, hasNext, hasPrev }`
    expect(Array.isArray(body.data)).toBe(true);
    expect(typeof body.total).toBe('number');
    expect(typeof body.page).toBe('number');
    expect(typeof body.limit).toBe('number');
  });

  it('POST /payment-terms then GET /:id — adapter CRUD smoke', async () => {
    // Asserts the new resource (extracted from invoice.resource.ts on
    // 2026-04-25) wires both the adapter create and per-id get correctly.
    const createRes = await server.inject({
      method: 'POST',
      url: `${API}/accounting/payment-terms`,
      headers: h(),
      payload: {
        name: 'NET 30 (e2e)',
        lines: [{ days: 30, percentage: 100 }],
        displayOnInvoice: true,
      },
    });
    expect(createRes.statusCode).toBe(201);
    const created = parse(createRes.body);
    expect(created._id).toBeDefined();
    expect(created.name).toBe('NET 30 (e2e)');

    const getRes = await server.inject({
      method: 'GET',
      url: `${API}/accounting/payment-terms/${created._id}`,
      headers: h(),
    });
    expect(getRes.statusCode).toBe(200);
    expect(parse(getRes.body)._id).toBe(created._id);

    // /:id/schedule still lives on this resource (computed projection,
    // raw route — see payment-term.resource.ts).
    const schedRes = await server.inject({
      method: 'POST',
      url: `${API}/accounting/payment-terms/${created._id}/schedule`,
      headers: h(),
      payload: { invoiceDate: '2026-04-25T00:00:00.000Z', totalAmount: 10000 },
    });
    expect(schedRes.statusCode).toBe(200);
    const sched = parse(schedRes.body);
    expect(Array.isArray(sched)).toBe(true);
    expect(sched.length).toBe(1);
  });

  it('POST /receipt — creates POS receipt', async () => {
    const res = await server.inject({
      method: 'POST',
      url: `${API}/accounting/invoices/receipt`,
      headers: h(),
      payload: {
        partnerId: 'walk-in',
        partnerName: 'Walk-in Customer',
        lines: [{ description: 'POS Sale', quantity: 1, unitPrice: 5000 }],
      },
    });

    expect(res.statusCode).toBe(200);
    const body = parse(res.body);
    expect(body.moveType).toBe('receipt');
    expect(body.status).toBe('posted');
  });
});

// ── 4. Streamline Workflows ─────────────────────────────────────────────────

describe('Workflow Integration', () => {
  it('GET /workflows — lists registered workflows', async () => {
    const res = await server.inject({
      method: 'GET',
      url: `${API}/workflows`,
      headers: h(),
    });

    // May be 200 or 404 depending on streamline registration timing
    if (res.statusCode === 200) {
      const body = parse(res.body);
      // Streamline plugin returns either the array directly or { data: [...] }.
      expect(Array.isArray(body) || Array.isArray(body?.data)).toBe(true);
    }
  });
});
