/**
 * Currency Exchange Rate Resource — Arc CRUD
 *
 * CRUD auto-generated by Arc via adapter. No custom routes needed.
 * Finance admins manage rates; the ManualRateBridge reads them.
 */

import { defineResource } from '@classytic/arc';
import { requireRoles } from '@classytic/arc/permissions';
import { QueryParser } from '@classytic/mongokit';
import { createAdapter } from '#shared/adapter.js';
import CurrencyExchangeRate from './exchange-rate.model.js';
import exchangeRateRepository from './exchange-rate.repository.js';

const queryParser = new QueryParser({
  maxLimit: 500,
  allowedFilterFields: ['fromCurrency', 'toCurrency', 'date', 'purpose', 'source'],
  allowedSortFields: ['date', 'fromCurrency', 'toCurrency', 'createdAt'],
});

export default defineResource({
  name: 'exchange-rate',
  prefix: '/accounting/exchange-rates',
  displayName: 'Exchange Rates',
  tag: 'Accounting - Exchange Rates',
  audit: true,
  adapter: createAdapter(CurrencyExchangeRate, exchangeRateRepository),
  queryParser,
  permissions: {
    list: requireRoles('admin', 'finance_admin', 'finance_manager'),
    get: requireRoles('admin', 'finance_admin', 'finance_manager'),
    create: requireRoles('admin', 'finance_admin'),
    update: requireRoles('admin', 'finance_admin'),
    delete: requireRoles('admin'),
  },
});
