import { defineResource } from '@classytic/arc';
import logisticsController from './logistics.controller.js';
import { logisticsActions } from '#shared/permissions.js';
import {
  getDivisionsSchema,
  getDistrictsSchema,
  getAreasSchema,
  searchAreasSchema,
  getZonesSchema,
  estimateChargeSchema,
  calculateChargeSchema,
  getConfigSchema,
  trackShipmentSchema,
  cancelShipmentSchema,
  getPickupStoresSchema,
  circuitStatusSchema,
  resetCircuitSchema,
  webhookSchema,
} from './logistics.schemas.js';
import { allowPublic } from '@classytic/arc/permissions';

const ctrl = logisticsController as Record<string, any>;

const logisticsResource = defineResource({
  name: 'logistics',
  displayName: 'Logistics',
  tag: 'Logistics',
  prefix: '/logistics',

  disableDefaultRoutes: true,

  additionalRoutes: [
    {
      method: 'GET',
      path: '/locations/divisions',
      summary: 'Get all divisions (8 divisions of Bangladesh)',
      permissions: logisticsActions.public,
      wrapHandler: false,
      schema: getDivisionsSchema,
      handler: ctrl.getDivisions,
    },
    {
      method: 'GET',
      path: '/locations/divisions/:division/districts',
      summary: 'Get districts by division',
      permissions: logisticsActions.public,
      wrapHandler: false,
      schema: getDistrictsSchema,
      handler: ctrl.getDistricts,
    },
    {
      method: 'GET',
      path: '/locations/areas',
      summary: 'Get all delivery areas',
      permissions: logisticsActions.public,
      wrapHandler: false,
      schema: getAreasSchema,
      handler: ctrl.getAreas,
    },
    {
      method: 'GET',
      path: '/locations/areas/search',
      summary: 'Search areas by name or post code',
      permissions: logisticsActions.public,
      wrapHandler: false,
      schema: searchAreasSchema,
      handler: ctrl.searchAreas,
    },
    {
      method: 'GET',
      path: '/locations/zones',
      summary: 'Get delivery zones with pricing info',
      permissions: logisticsActions.public,
      wrapHandler: false,
      schema: getZonesSchema,
      handler: ctrl.getDeliveryZones,
    },
    {
      method: 'GET',
      path: '/locations/estimate',
      summary: 'Estimate delivery charge (static calculation)',
      permissions: logisticsActions.public,
      wrapHandler: false,
      schema: estimateChargeSchema,
      handler: ctrl.estimateCharge,
    },
    {
      method: 'GET',
      path: '/charge',
      summary: 'Calculate charge via provider API',
      description: 'Fetches real-time pricing from the shipping provider',
      permissions: logisticsActions.public,
      wrapHandler: false,
      schema: calculateChargeSchema,
      handler: ctrl.calculateCharge,
    },
    {
      method: 'GET',
      path: '/config',
      summary: 'Get logistics configuration (read-only from .env)',
      description: 'Configuration is managed via environment variables. Restart server after changes to .env file.',
      permissions: logisticsActions.admin,
      wrapHandler: false,
      schema: getConfigSchema,
      handler: ctrl.getConfig,
    },
    {
      method: 'GET',
      path: '/shipments/:id/track',
      summary: 'Track shipment via provider API',
      description: 'Fetches live tracking info from the shipping provider. Use order ID or tracking number.',
      permissions: logisticsActions.manage,
      wrapHandler: false,
      schema: trackShipmentSchema,
      handler: ctrl.trackShipment,
    },
    {
      method: 'POST',
      path: '/shipments/:id/cancel',
      summary: 'Cancel shipment via provider API',
      description: 'Cancels the shipment in the provider system. Use order ID or tracking number.',
      permissions: logisticsActions.manage,
      wrapHandler: false,
      schema: cancelShipmentSchema,
      handler: ctrl.cancelShipment,
    },
    {
      method: 'GET',
      path: '/pickup-stores',
      summary: 'Get pickup stores from provider',
      permissions: logisticsActions.manage,
      wrapHandler: false,
      schema: getPickupStoresSchema,
      handler: ctrl.getPickupStores,
    },
    {
      method: 'GET',
      path: '/health/circuit-status',
      summary: 'Get circuit breaker status for all providers',
      permissions: logisticsActions.admin,
      wrapHandler: false,
      schema: circuitStatusSchema,
      handler: ctrl.getCircuitStatus,
    },
    {
      method: 'POST',
      path: '/health/circuit-reset/:provider',
      summary: 'Reset circuit breaker for a provider',
      permissions: logisticsActions.admin,
      wrapHandler: false,
      schema: resetCircuitSchema,
      handler: ctrl.resetProviderCircuit,
    },
    {
      method: 'POST',
      path: '/webhooks/:provider',
      summary: 'Handle logistics provider webhook',
      description: 'Receives status updates from shipping providers (RedX, Steadfast, etc.)',
      permissions: allowPublic(),
      wrapHandler: false,
      schema: webhookSchema,
      handler: ctrl.handleWebhook,
    },
  ],
});

export default logisticsResource;
